- README.md
Link for `Testing in Terminal` in README is broken.
Use the correct name for the link.
@mikkoh
> fixing README link to Testing in Terminal

- Assets/Editor/TestCart.cs
- Assets/Shopify/examples.txt.meta
- scripts/generator/graphql_generator/csharp.rb
- scripts/generator/graphql_generator/csharp/Cart.cs.erb
- scripts/generator/graphql_generator/csharp/SDK/CartLineItems.cs.erb
- scripts/generator/graphql_generator/csharp/SDK/ObservableDictionary.cs.erb
- scripts/test_unity.sh
This PR refactors cart line items to be a new generic type called `CartLineItem` from `CheckoutLineItemInput`.
At one time for checkouts `CheckoutLineItemInput` was the only input type for creating line items but now that we have `CheckoutLineItemUpdateInput` also I felt it's important to have a generic line item type type for the Cart from which we can create `CheckoutLineItemInput's` and `CheckoutLineItemUpdateInput's`.
The saved boolean will be used to determine when updates are done instead of creations.
> [FIX] Refactor CartLineItem to be generic

- Assets/Editor/TestDefaultQueriesCheckout.cs
- scripts/generator/graphql_generator/csharp.rb
- scripts/generator/graphql_generator/csharp/SDK/DefaultQueries.cs.erb
- scripts/generator/graphql_generator/csharp/SDK/DefaultQueriesCheckout.cs.erb
This PR adds default queries we'll need to start to build checkouts via weblink.
The following queries are included:
* creating checkouts
* updating checkouts
+ Add line items
+ Remove line items
+ Update line items
* Poll to wait for `ready`
The following queries are not included:
* Setting up shipping information
* Discounts
* Completing checkouts
> [FEATURE] Added default queries for checkout

- Assets/Editor/TestDefaultQueriesCheckout.cs
It seems that the attribute order has changed in the schema. This broke one of the tests.
> [Fix] Test default query add line items

- scripts/common.sh
- scripts/generator/graphql_generator/csharp/SDK/ObservableDictionary.cs.erb
- scripts/test_unity.sh
+ Removes incorrect whitespace that caused older versions of Mono to have parsing issues
+ Adds ./ to correct test path errors
+ Adds Print statement to output the version of Unity
+ Removes -quit flag from build, -runEditorTests will quit upon failure or success
> [FIX] CI compile parsing error

- Assets/Editor/TestCart.cs
- Assets/Editor/TestDefaultQueriesCheckout.cs
- scripts/generator/graphql_generator/csharp/SDK/CartLineItems.cs.erb
This PR creates 3 lists of line items on `CartLineItems`:
* New line items
* Modified line items
* Deleted line items
This will allow us build queries to create, modify, delete line items in the Storefront API.
> [Feature] Split line items into new, modified, and deleted

- EXAMPLES.md
- scripts/generator/graphql_generator/csharp/ShopifyBuy.cs.erb
We have an issue right now where it's hard for us to tell in Splunk whether queries are coming from people testing the SDK or if it's from Integration tests. This PR updates the store url and access token to use a test shop `unity-buy-sdk.myshopify.com`.
This update will allow us to differentiate better in Splunk whether developers are testing the sdk based on the SDK documentation or if it's queries are coming from internal development.
> [FIX] Created a `unity-buy-sdk` test store

- Assets/Editor/TestDefaultQueriesCheckout.cs.meta
- scripts/generator/graphql_generator/csharp.rb
- scripts/generator/graphql_generator/csharp/SDK/GlobalGameObject.cs.erb
- scripts/generator/graphql_generator/csharp/SDK/UnityLoader.cs.erb
This PR allows you to add components to a global `GameObject`. Previously the `UnityLoader` had it's own `GameObject`. Now for checkouts we need to add the ability to poll on an interval we we need to have `GameObject` to add a script to. Instead of all these scripts creating their own `GameObjects` it's probably better we just have one global game object.
> [Feature] Global GameObject

- Assets/Editor/BaseMockLoader.cs.meta
- Assets/Editor/IMockLoader.cs.meta
- Assets/Editor/MockLoaderCollections.cs.meta
- Assets/Editor/MockLoaderErrors.cs.meta
- Assets/Editor/MockLoaderGeneric.cs.meta
- Assets/Editor/MockLoaderProducts.cs.meta
- Assets/Editor/TestMockLoaders.cs.meta
- Assets/Editor/TestResponeMergeUtil.cs
- Assets/Editor/TestResponeMergeUtil.cs.meta
- Assets/Editor/UtilsMockLoader.cs.meta
- Assets/Shopify/examples.txt.meta
- scripts/generator/graphql_generator/csharp.rb
- scripts/generator/graphql_generator/csharp/SDK/AbstractResponse.cs.erb
- scripts/generator/graphql_generator/csharp/SDK/ResponseMergeUtil.cs.erb
This PR implements the ability to merge response json objects.
When working with checkouts we want the ability to update a previously queried `Checkout`. For instance let's say that we are polling we want to update `ready` on an existing `Checkout` we've previously queried.
One curious thing in this PR is `DoNotMergeIfExists`. There maybe cases where we do not want to merge one field but merge all other fields. This for instance could be used when you want to handle a field on a case by case basis. For instance with `Checkouts` sometimes we may want to merge in line items sometimes we may want to leave them be.
> [Feature] Merge utils

- scripts/generator/graphql_generator/csharp/Editor/ExtendedPBXProject.cs.erb
- scripts/generator/graphql_generator/csharp/Editor/PostProcessor.cs.erb
- scripts/generator/graphql_generator/csharp/Editor/ShopifyIosPostProcessor.cs.erb
Some of the files added require Unity specific classes the following adds preprocessor conditionals to ensure we can run tests in mono via `scripts/test.sh`
> [Fix] Testing in mono

- Assets/Plugins/iOS/Shopify/BuyTests/DeserializableTests.swift
- Assets/Plugins/iOS/Shopify/BuyTests/DeserializableTests.swift.meta
- Assets/Plugins/iOS/Shopify/BuyTests/Models/Models.swift
+ Adds deserializable tests
+ Adds conveniences for constructing JSONs in models
<hr>
+ Decided to re-create the enum fields for [`PKPaymentSummaryItem`](https://github.com/Shopify/unity-buy-sdk/blob/beta/Assets/Plugins/iOS/Shopify/Deserializable/PKPaymentSummaryItem%2BDeserializable.swift) and [`PKShippingMethod`](https://github.com/Shopify/unity-buy-sdk/blob/beta/Assets/Plugins/iOS/Shopify/Deserializable/PKShippingMethod%2BDeserializable.swift) in models because they are marked private in the implementation.
+ Since `PKShippingMethod` is a subclass of  `PKPaymentSummaryItem` and we cannot override enums, the `Field` enum must be marked private.
> [Feature] iOS Deserializable Tests

- Assets/Plugins/iOS/Shopify/BuyTests/CartTests.swift
- Assets/Plugins/iOS/Shopify/BuyTests/CartTests.swift.meta
- Assets/Plugins/iOS/Shopify/Cart+ApplePay.h
- Assets/Plugins/iOS/Shopify/Cart+ApplePay.h.meta
- Assets/Plugins/iOS/Shopify/Cart+ApplePay.mm
- Assets/Plugins/iOS/Shopify/Cart+ApplePay.mm.meta
- Assets/Plugins/iOS/Shopify/Cart+ApplePay.swift
- Assets/Plugins/iOS/Shopify/Cart+ApplePay.swift.meta
- Assets/Plugins/iOS/Shopify/Deserializable/PKPaymentSummaryItem+Deserializable.swift
- Assets/Plugins/iOS/Shopify/Deserializable/PKShippingMethod+Deserializable.swift
+ Defines the methods that managed code can access in order to interact with a `PaymentSession` 
+ Adds tests that check arguments are parsed into a `PaymentSession` correctly
+ The serialized summary items and shipping items are stored in a `[String: String]` with a key of `Items` 
+ The built in serializable in `C#` for `List` must have it as a value of a `Dictionary`, hence the extra wrapping
> [Feature] iOS Cart Apple Pay

- scripts/generator/graphql_generator/csharp/Cart.cs.erb
+ Puts the polling functionality for a checkout into separate method
+ By moving the polling function out, we can now poll for any `Ready` fields on `Checkout` specifically `ShippingLines`
> [Feature] Ready Poll

- README.md
Newer versions of Mono give a warning that NUnit is deprecated
> Add version of mono in README

- scripts/generator/graphql_generator/csharp.rb
- scripts/generator/graphql_generator/csharp/SDK/CartLineItems.cs.erb
- scripts/generator/graphql_generator/csharp/SDK/ConnectionLoader.cs.erb
- scripts/generator/graphql_generator/csharp/SDK/Delegates.cs.erb
- scripts/generator/graphql_generator/csharp/SDK/ILoader.cs.erb
- scripts/generator/graphql_generator/csharp/SDK/ObservableDictionary.cs.erb
- scripts/generator/graphql_generator/csharp/SDK/QueryLoader.cs.erb
- scripts/generator/graphql_generator/csharp/SDK/ResponseMergeUtil.cs.erb
- scripts/generator/graphql_generator/csharp/ShopifyBuy.cs.erb
Moves all of the delegates we use into a single SDK/Delegates.cs.erb file. Also changes the only Action<> we used for CartLineItems to be a delegate instead.
> Move Delegates to Single File

- scripts/generator/graphql_generator/csharp/type.cs.erb
- Adds a constructor for Input types to be created from a JSON dictionary. 
- By adding this constructor, Input types such as `MailingAddressInput` can be constructed from the serialized json objects sent from unmanaged functions
- Decided to re-throw any exceptions. But at the call site we would probably not use a try and catch since a failure to initialize meant there is an error with our SDK
> [Feature] Input JSON Constructor

- Assets/Editor/TestDefaultQueriesCheckout.cs
- scripts/generator/graphql_generator/csharp/SDK/NativeMessage.cs.erb
- scripts/generator/graphql_generator/csharp/SDK/Serializable.cs.erb
Wraps UnityEngine-required tests with #ifdef check and removes unused import.
> Ignore UnityEngine.dll-required files for Mono unit tests

- scripts/generator/graphql_generator/csharp.rb
- scripts/generator/graphql_generator/csharp/Cart.cs.erb
- scripts/generator/graphql_generator/csharp/SDK/iOS/Cart.ApplePayEventReceiver.cs.erb
- scripts/generator/graphql_generator/csharp/SDK/iOS/CartApplePayEventReceiver.cs.erb
- scripts/generator/graphql_generator/csharp/SDK/iOS/ShippingMethod.cs.erb
+ Adds an Apple Pay Receiver to `Cart`
+ Received serialized Shipping and Email information from Apple Pay are deserialized and sent as GraphQL mutations
+ Combines email and shipping mutation queries, since they are not used separately 
+ Unit Tests
+ Will write the unit tests once we can create an apple pay session from Unity 
+ Error Refactors
+ Will leave the refactoring of Cart.cs later on to use Shopify Error
> [Feature] Cart Apple Pay Shipping

- scripts/generator/graphql_generator/csharp.rb
- scripts/generator/graphql_generator/csharp/Cart.Poll.cs.erb
- scripts/generator/graphql_generator/csharp/Cart.cs.erb
- scripts/generator/graphql_generator/csharp/SDK/Delegates.cs.erb
- scripts/generator/graphql_generator/csharp/ShopifyBuy.cs.erb
+ Adds a generalized polling function to `ShopifyBuy` Client
+ Since are a few graphql queries that use `ready` we need to be able to poll for those
+ Checkout
+ Available Shipping Rates
+ Payment
+ Decided to put this function in `ShopifyBuy`  since it is generally just making a graphql query
+ Chose to put the polling methods into a separate partial class to keep the `Cart` file from being bloated
> [Feature] Poll refactor

- scripts/generator/graphql_generator/csharp.rb
- scripts/generator/graphql_generator/csharp/SDK/INativeCheckout.cs.erb
- scripts/generator/graphql_generator/csharp/SDK/iOS/iOSNativeCheckout.cs.erb
+ Adds interface for native payable
+ Adds iOS native pay implementation 
+ Chose to have `key` passed into `StartCheckout(string key)` instead of when we instantiate a `iOSNativePayable`.
+ When `iOSNativePayable` is instantiated in the constructor of `Cart` following #114 we do not have the `merchantId` yet
> [Feature] iOS Native Payable Structure

- Assets/Editor/MockLoaderCheckouts.cs
- Assets/Editor/TestCart.cs
- scripts/generator/graphql_generator/csharp/Cart.Poll.cs.erb
- scripts/generator/graphql_generator/csharp/Cart.cs.erb
- scripts/generator/graphql_generator/csharp/SDK/NativeMessage.cs.erb
- scripts/generator/graphql_generator/csharp/SDK/Serializable.cs.erb
- scripts/generator/graphql_generator/csharp/SDK/ShopifyError.cs.erb
I was working on an example of how we could handle user errors.
Really user errors describe one of the states of the checkout that is not defined in `Checkout`. This state is that the `Checkout` can be in erroneous state. So my thought was to add the list of user errors to the `Cart` beside `CurrentCheckout`.
This list should be exposed to the user. I think with the work that @sleroux has been doing on refactoring errors we could send an error that is of type user error and in documentation we tell the user to check user errors on cart.
Thoughts? This PR should be finished after #107.
> [Feature] User Error Handling

- scripts/generator/graphql_generator/csharp/SDK/ShopifyError.cs.erb
- scripts/generator/graphql_generator/csharp/SDK/iOS/iOSNativeCheckout.ApplePayEventReceiver.cs.erb
- scripts/generator/graphql_generator/csharp/SDK/iOS/iOSNativeCheckout.cs.erb
* Parses PaymentStatus from iOS to determine which callback to fire on the C# side.
* Introduces the CheckoutError error type to ShopifyError
> [Feature] Implements DidFinishCheckoutSession for iOSNativeCheckout

- scripts/generator/graphql_generator/csharp/Cart.cs.erb
* Adds `SetFinalCheckoutFields` method for combining the 3 update query calls into one.
* Adds `ShippingFields` to enclose the shipping address and identifier since the update query either has both or none of those properties.
I'll follow this PR up with tests on TestCart.cs
> [Feature] Combines SetEmailUpdate/SetShippingAddress/SetShippingLine into SetFinalCheckoutFields method

- Assets/Editor/BuildPipeline/ShopifyBuildPipeline.cs
- Assets/Editor/TestDefaultQueriesCheckout.cs
- scripts/generator/graphql_generator/csharp.rb
- scripts/generator/graphql_generator/csharp/Cart.cs.erb
- scripts/generator/graphql_generator/csharp/SDK/DefaultQueriesCheckout.cs.erb
- scripts/generator/graphql_generator/csharp/SDK/iOS/ApplePayPayment.cs.erb
- scripts/generator/graphql_generator/csharp/SDK/iOS/PaymentDeserializer.cs.erb
- scripts/generator/graphql_generator/csharp/SDK/iOS/iOSNativeCheckout.ApplePayEventReceiver.cs.erb
Requires #153, so I set to temporary merge into that branch
+ Implements checkout with token and error handling
+ Adds missed deserializations for Payment
+ Adds Simulator compile time flag
When handling Apple Pay errors, if more than one error is present such as `InvalidShippingContact` or `InvalidShippingAddress`, it doesn't matter which one we return, we can only return one at a time, so it is random to which one is returned
> [Feature] Apple Pay checkout token

- Assets/Plugins/iOS/Shopify/BuyTests/CartTests.swift
Since MiniJson serializes each Summary item and shipping method to a string and then serializes and array of them, I refactored the tests to fit this.
> [Fix] Cart tests for new MiniJson serialization

- Assets/UnityTestTools/NativeTesting/iOS/ApplePayEventTester.cs
Resolves the random issue where the ApplePayEventTester script was not being recognized in the Unity editor correctly.
> [Fix] Splits up Tester behaviour into Unity/iOS friendly parts to avoid editor issues

- Assets/Editor/MockLoaderCheckouts.cs
- Assets/Editor/iOS/TestWebCheckout.cs
- scripts/generator/graphql_generator/csharp/SDK/iOS/iOSWebCheckout.cs.erb
Using https://github.com/Shopify/unity-buy-sdk/pull/171 as a base, this patch adds new tests for the web checkout's core logic that lives in `OnNativeMessage`.
> [Tests] Adds tests for iOS Web Checkouts OnNativeMessage

- Assets/Plugins/iOS/Shopify/WebCheckoutSession.swift
To resolve both the status bar and push animation issues, I've wrapped the SFSafariViewController with a custom UINavigationController. The custom UINavigationController will also constrain the rotation allowed to whatever the game supports. If the game is landscape only, the controller will only be landscape!
> [Fix] Fixes presentation and status bar issues with safari view controller for web checkouts

- scripts/generator/graphql_generator/csharp/SDK/iOS/iOSWebCheckout.cs.erb
Fixes random compile issue in Unity by moving the properties to public for now. This will be cleaned up when we do the public API audit.
> [Fix] Moves iOSWebViewMessageReceiver properties to public temporarily

- Assets/Editor/MockLoaderCheckouts.cs
- Assets/Editor/iOS/TestWebCheckout.cs
- scripts/generator/graphql_generator/csharp/SDK/iOS/iOSWebCheckout.cs.erb
Before, we were only ever invoking success when a checkout has a completedAt date or failure when it doesn't. In the case of cancelling the web checkout, the failure callback was being invoked instead of cancelled. It doesn't make much sense to 'fail' when the user just 'cancelled' so this patch will only call the failure callback if we ran into some kind of failure communicating with our API and calls cancelled if we don't see the completedAt date. This means that in cases of spoofing the web view that it will come back as cancelled but that seems like an edge case.
> [Fix] Adds cancelled state handling for web checkouts and tests

- scripts/generator/graphql_generator/csharp.rb
- scripts/generator/graphql_generator/csharp/SDK/NativeMessage.cs.erb
- scripts/generator/graphql_generator/csharp/SDK/iOS/IApplePayEventReceiver.cs.erb
- scripts/generator/graphql_generator/csharp/SDK/iOS/iOSNativeCheckout.cs.erb
- scripts/generator/graphql_generator/csharp/SDK/iOS/iOSWebCheckout.cs.erb
- scripts/generator/graphql_generator/csharp/SDK/iOS/iOSWebViewMessageReceiver.cs.erb
- scripts/test.sh
* Defines UNITY_IOS preproccessor in test script mcs command to include all iOS dependent classes.
* Moves iOSWebViewMessageReceiver into it's own class for easier #ifdef exclusion for SHOPIFY_MONO_UNIT_TEST/UNITY_IOS.
* Removed not needed UnityEngine import for NativeMessage.cs.erb and wrapped extern call with !SHOPIFY_MONO_UNIT_TEST.
* Split ApplePayEventReceiverBridge.cs.erb into 2 partial classes to isolate MonoBehaviour subclassing.
> [Refactor] Refactors classes/methods that rely on UNITY_IOS to support monotesting.

- scripts/generator/graphql_generator/csharp/Cart.cs.erb
- scripts/generator/graphql_generator/csharp/CartState.cs.erb
Git didn't pick up the changes between CartState and the Reset patch so this resolves the compilation issue and moves the Reset method into CartState.
> [Fix] Moves reset logic into CartState

- Assets/Plugins/iOS/Shopify/BuyTests/PaymentSessionTests.swift
- Assets/Plugins/iOS/Shopify/PaymentSession.swift
+ Sets the capabilities and networks that Shopify Pay uses, until we can fetch those from the Storefront API
> Added capabilites and default networks to PaymentSession

- scripts/generator/graphql_generator/csharp.rb
- scripts/generator/graphql_generator/csharp/Cart.cs.erb
- scripts/generator/graphql_generator/csharp/SDK/DefaultQueries.cs.erb
- scripts/generator/graphql_generator/csharp/SDK/DefaultShopQueries.cs.erb
- scripts/generator/graphql_generator/csharp/SDK/Delegates.cs.erb
- scripts/generator/graphql_generator/csharp/SDK/INativeCheckout.cs.erb
- scripts/generator/graphql_generator/csharp/SDK/iOS/iOSNativeCheckout.cs.erb
- scripts/generator/graphql_generator/csharp/ShopifyBuy.cs.erb
+ Adds queries for PaymentSettings of a Store
+ Uses the country code from payment settings
Since we need to fetch the payment settings of a store before we can perform a checkout, we fetch it only when it is needed instead of when the `Cart` is created. 
+ By doing this we have to pass in `PaymentSettings` through the methods in the INativePayment interface
+ Users who are already using the SDK don't have to make any changes
+ Users who don't need to support Apple Pay don't need to make the PaymentSettings query
> [Fix] Use store country code for payment session

- Assets/Plugins/iOS/Shopify/BuyTests/ApplePayFlowTests.swift
- scripts/generator/graphql_generator/csharp/SDK/iOS/iOSNativeCheckout.ApplePayEventReceiver.cs.erb
+ Added check to see if there is one shipping method 
+ When there is one, update shipping lines immediately
+ When there is one shipping method, Apple does not call the delegate method for selecting a shipping line item.
+ Shopify Admin does not update the checkout query `Total`when there is only one shipping method, this seems like a bug.
+ You can checkout without selecting a shipping line item, and the total Shopify expects includes the single shipping cost when trying to complete a checkout
> [Fix] Added handling for single shipping rates

- scripts/generator/graphql_generator/csharp/Cart.cs.erb
- scripts/generator/graphql_generator/csharp/ShopifyBuy.cs.erb
Should be noted this PR is merging onto `master`.
This PR removes `paymentSettings` from the client and just adds the query functionality to `Cart`.
> [Refactor] Payment Settings

- scripts/generator/graphql_generator/csharp/Cart.cs.erb
- scripts/generator/graphql_generator/csharp/SDK/DefaultShopQueries.cs.erb
- scripts/generator/graphql_generator/csharp/SDK/Delegates.cs.erb
- scripts/generator/graphql_generator/csharp/SDK/INativeCheckout.cs.erb
- scripts/generator/graphql_generator/csharp/SDK/iOS/iOSNativeCheckout.cs.erb
Android Pay requires a merchant name so this patch appends to the existing GraphQL query we're making to get the payment settings to get the shop name.
> [Feature] Adds caching for Shop's name whenever we fetch PaymentSettings

- scripts/publish.sh
+ Adds a variable that records the build return value
+ Changes the if statement to check for that value instead of the return value of `restore_native_tests`
> [Fix] Check publish.sh build's return value

- scripts/generator/graphql_generator/csharp/SDK/WebCheckout.cs.erb
Adds compile flags that removes the warning for `GlobalGameObject` not being defined, since `GlobalGameObject` is only defined when compiling for non Mono test
> [Fix] Webcheckout mono tests

- scripts/generator/graphql_generator/csharp/SDK/Android/AndroidWebCheckout.cs.erb
- scripts/generator/graphql_generator/csharp/SDK/WebCheckout.cs.erb
- scripts/generator/graphql_generator/csharp/SDK/iOS/iOSWebCheckout.cs.erb
+ Since implementations of `WebCheckout` are not the ones adding a `NativeMessageReceiver` it makes sense that they should not be the ones to dictate what the name of the receiver is
> [Fix] Hide web checkout message receiver name

- scripts/generator/graphql_generator/csharp/Editor/ShopifyOnboardingPanel.cs.erb
There was a bug where the window was showing up in the wrong size on
some machines. This specifies a rect size for the window in its spawning
function, and specifies a minimum size for the window so that it is not
resizable and contains all of the content at all times.
This is a bit of a yolofix because I was unable to reproduce the bug, but this approach has its own merits outside of fixing that bug specifically (unresizable window for example)
> [Fix] Use EditorWindow.GetWindowWithRect and specify minSize for popup

- scripts/native_tests.sh
+ Only the files that were removed should be checked-out to avoid checking out other files that have changes. Useful for debugging.
+ Used `*` to handle `.meta` files
> [Fix] Publish removing android files

- scripts/activate_license.sh
- scripts/deactivate_license.sh
- scripts/has_license_credentials.sh
+ Refactors the script to follow common practices
+ Resolves most of the lint errors thrown by `shellcheck`
+ Fixes #190, by moving license check to a function
> [Refactor] license scripts to fix lint issues and fixes #190

- scripts/build.sh
- scripts/common.sh
- scripts/generate.sh
- scripts/generator/graphql_generator/csharp.rb
- scripts/generator/graphql_generator/csharp/Editor/ShopifyOnboardingPanel.cs.erb
- scripts/generator/update_schema
- scripts/publish.sh
- scripts/test_watch.sh
This PR implements having the ability to generate different source for the Unity Buy SDK based on the distribution platform we hit. Mainly we do this for tracking purposes so we can see where signups come from. For instance the `ShopifyOnboardingPanel.cs` looks like this when distributing to Github:
```
if (GUILayout.Button("Start your free trial", Styles.ButtonStyle))
Application.OpenURL("https://www.shopify.ca/signup?signup_types=unity_buy_sdk,github");
```
And for `asset-store`:
```
if (GUILayout.Button("Start your free trial", Styles.ButtonStyle))
Application.OpenURL("https://www.shopify.ca/signup?signup_types=unity_buy_sdk,asset-store");
```
> [Feature] Asset Store Build

- Assets/Plugins/iOS/Shopify/BuyTests/ApplePayFlowTests.swift
+ Before we were using calculated shipping rates, so the identifier was not static. This PR changes the expected shipping methods to match the fixed rates that are now set on the example store.
> [Fix] iOS tests that use shipping method identifier

- Assets/Editor/BuildPipeline/ShopifyBuildPipeline.cs
- Assets/Editor/BuildPipeline/iOSTestPostProcessor.cs
- Assets/UnityTestTools/NativeTesting/iOS/ApplePayEventTesterReceiver.cs
- scripts/generator/graphql_generator/csharp/Editor/BuildPipeline/ExtendedPBXProject.cs.erb
- scripts/generator/graphql_generator/csharp/Editor/BuildPipeline/iOSPostProcessor.cs.erb
- scripts/test_iOS.sh
On machines that don't support the iOS player (like Windows), the package won't compile because of errors with the iOS-only build pipeline scripts.
> [Fix] Adds UNITY_IPHONE checks to build pipeline scripts

- scripts/generator/graphql_generator/csharp/Cart.cs.erb
- scripts/generator/graphql_generator/csharp/SDK/Delegates.cs.erb
- scripts/generator/graphql_generator/csharp/SDK/INativeCheckout.cs.erb
- scripts/generator/graphql_generator/csharp/SDK/iOS/iOSNativeCheckout.cs.erb
+ Makes `canShowPaymentSetup` asynchronous because we need to fetch the shop's payment settings
> [Fix] Native checkout supported payment network

- Assets/Plugins/iOS/Shopify/BuyTests/CartTests.swift
- Assets/Plugins/iOS/Shopify/BuyTests/Models/Models.swift
- Assets/Plugins/iOS/Shopify/BuyTests/PaymentSessionTests.swift
- Assets/Plugins/iOS/Shopify/Cart+ApplePay.h
- Assets/Plugins/iOS/Shopify/Cart+ApplePay.mm
- Assets/Plugins/iOS/Shopify/Cart+ApplePay.swift
- Assets/Plugins/iOS/Shopify/PaymentSession.swift
- scripts/generator/graphql_generator/csharp/SDK/iOS/iOSNativeCheckout.cs.erb
+ Adds serialized supported payment networks as a parameter to the checkout related methods in iOS. 
+ Removes static supported payment networks in favour of the values passed through `PaymentSettings`
> [Feature] Checkout with supported networks

- android/shopify_buy_plugin/src/androidTest/java/com/shopify/unity/buy/UnityAndroidPayFragmentTest.java
- android/shopify_buy_plugin/src/main/java/com/shopify/unity/buy/AndroidPayCheckoutSession.java
- android/shopify_buy_plugin/src/main/java/com/shopify/unity/buy/AndroidPaySessionCallback.java
- android/shopify_buy_plugin/src/main/java/com/shopify/unity/buy/MessageCenter.java
- android/shopify_buy_plugin/src/main/java/com/shopify/unity/buy/UnityAndroidPayFragment.java
Calling the message sender caushes a crash on the Android side and after giving it some thought realized that we don't actually need it at all. We can simply call the Unity send message commands. So I did just that.
> [Fix] Removes usage of handler/looper from MessageCenter

- scripts/generator/graphql_generator/csharp.rb
- scripts/generator/graphql_generator/csharp/SDK/Android/AndroidNativeCheckout.AndroidPayEventReceiver.cs.erb
- scripts/generator/graphql_generator/csharp/SDK/Android/AndroidNativeCheckout.cs.erb
- scripts/generator/graphql_generator/csharp/SDK/Android/AndroidPayEventReceiverBridge.cs.erb
- scripts/generator/graphql_generator/csharp/SDK/Android/IAndroidPayEventReceiver.cs.erb
Mirrors the same technique we used for passing messages from iOS to Unity but for Android. Stubbed out the receiver calls in the partial extension off of AndroidNativeCheckout.
> [Android Pay] Adds interface for bridging calls between Android and Unity 

- android/shopify_buy_plugin/build.gradle
+ copyAARToPlugins does not run every time or run in order sometimes. Adding these flags ensures that it is never `UP-TO-DATE` and runs after compiling
> [Fix] Android Gradle copy order

- Assets/Plugins/Android/AndroidManifest.xml
- Assets/Plugins/Android/AndroidManifest.xml.meta
- android/shopify_buy_plugin/src/main/AndroidManifest.xml
- android/shopify_buy_plugin/src/main/java/com/shopify/unity/buy/AndroidPayCheckoutSession.java
- android/shopify_buy_plugin/src/main/java/com/shopify/unity/buy/ShopifyUnityPlayerActivity.java
Adds a custom Activity override on UnityPlayerActivity to work around a bug with Android Pay where onActivityResult is not fired to child fragments when the wallet chooser is dismissed.
> [Android Pay] Adds custom override on UnityPlayerActivity in order to forward onActivityResult to fragments

- android/shopify_buy_plugin/src/androidTest/java/com/shopify/unity/buy/WebIntentFragmentTest.java
- android/shopify_buy_plugin/src/main/java/com/shopify/unity/buy/WebIntentFragment.java
Converts the old web intent test from using roboelectric to using the instrument integration test on device.
> [Cleanup] Adds instrument test for web intent listener

- scripts/test.sh
`recurse:'Assets/Editor/*.cs'` is sufficient to include the `iOS` specific files
> [Fix] Removed extra recurse source definition in tests

- Assets/Plugins/iOS/Shopify/BuyTests/Mocks/MockAuthorizationController.swift
- Assets/Plugins/iOS/Shopify/PaymentSession.swift
+ Merging into `ios-11-support` because this is not backwards compatible with versions older than Xcode 9
+ Adds new delegate methods that were added to `PassKit`
+ They are left blank for now until we are ready to handle them 
+ In the new delegate calls, PKPaymentRequestShippingContactUpdate and PKPaymentAuthorizationResult classes expects an array of PKError for initialization. Since errors are marshalled in from managed code, we have not implemented the functionality for creating PKError from the Storefront APIs.
CI will be failing for now, since iOS 11 requires the CI to use a beta version of Unity and Xcode. Bringing CI up to par will be done in another PR
> Added necessary changes for compiling on iOS 11

- scripts/generator/graphql_generator/csharp/CartState.cs.erb
Small refactor to make extra clear which way the sync is going with these methods. I am expecting that in introducing the IsCompleted method to the Cart that we will need an UpdateLocalStateFromRemoteCheckout, so it makes sense to disambiguate here.
cc @Shopify/gaming
> rename methods to clarify direction of sync

- scripts/generator/graphql_generator/csharp/type.cs.erb
+ Adds string constants that reflect the naming of each field
+ Does not follow C# naming conventions, capitalizing fields would add unneeded complexity
+ We do not use Enums, incase a field is named the same as a reserved word
+ Since `UserErrors` directly map to an Input type's field, it would be safer to compare that the `UserError` is equivalent to variable rather than a string. This allows us to have compile time safety when/if the API for the input type changes
> [Feature] Input field constants

- scripts/generator/graphql_generator/csharp.rb
- scripts/generator/graphql_generator/csharp/SDK/Android/AndroidNativeCheckout.AndroidPayEventReceiver.cs.erb
- scripts/generator/graphql_generator/csharp/SDK/Android/NativeMessage.Android.cs.erb
- scripts/generator/graphql_generator/csharp/SDK/NativeMessage.cs.erb
- scripts/generator/graphql_generator/csharp/SDK/iOS/NativeMessage.iOS.cs.erb
Splits up NativeMessage into platform-dependent partial classes so we can use the same logic for Android message handling.
> [Refactor] Splits NativeMessage into Android/iOS parts

- scripts/generator/graphql_generator/csharp/SDK/iOS/ApplePayAddressInvalidError.cs.erb
- scripts/generator/graphql_generator/csharp/SDK/iOS/ApplePayBillingAddressInvalidError.cs.erb
- scripts/generator/graphql_generator/csharp/SDK/iOS/ApplePayContactInvalidError.cs.erb
- scripts/generator/graphql_generator/csharp/SDK/iOS/ApplePayShippingAddressInvalidError.cs.erb
+ Adds constructors to `ApplePayErrors` that take in a `MailingAddressInput` field.
+ An incorrect value for a field in `MailingAddressInput` causes a `UserError` with `MailingAddressInput` fields. Since `ApplePayErrors` represent `UserErrors` when making requests related to Apple Pay, it should be that a `MailingAddressInput` field is mapped to an `ApplePayError`
> [Feature] Added constructor to errors that takes in a MailingAddressInputField

- scripts/generator/graphql_generator/csharp/Editor/BuildPipeline/iOSPostProcessor.cs.erb
Fixes https://github.com/Shopify/unity-buy-sdk-examples/issues/17
> UNITY_IOS  #define directive for compiling/executing code for the iOS platform.
https://docs.unity3d.com/Manual/PlatformDependentCompilation.html
It appears we were actually already using conditional compilation here, we just need to make a bit of an adjustment so that the using statements are omitted as well, unless doing an ios build.
@Shopify/gaming @pushmatrix
> omit includes for iOSPostProcessor unless on ios

- scripts/generator/graphql_generator/csharp/SDK/iOS/ApplePayShippingAddressInvalidError.cs.erb
- scripts/generator/graphql_generator/csharp/SDK/iOS/iOSNativeCheckout.ApplePayEventReceiver.cs.erb
+ Fixes typo causing shipping address errors to e handled like billing address error
+ Adds shipping error handling within checkout user errors.
+ Setting a checkout to allow partial addresses voids the validation when making update address queries. So the addresses are validated on the checkout mutation
> [Fix] Apple pay error handling

- Assets/Editor/TestCart.cs
- Assets/NativeTesting/iOS/ApplePayFlowTester.cs
- EXAMPLES.md
- scripts/generator/graphql_generator/csharp/SDK/CartLineItems.cs.erb
Per https://github.com/Shopify/unity-buy-sdk/pull/297/files#r135104239, changes the `AddOrUpdate` overloads to remove the option to add via variantId, preferring instead to only have the overloads for passing a ProductVariant, or a Product/options. 
Rationale is that as we use more attributes from the ProductVariant we want to be able to control how the attributes are associated with the CartLineItems.
> Remove variant id only overload

- scripts/generator/graphql_generator/csharp/Cart.cs.erb
Sets AndroidNativePayment to null for now until native Android Pay is implemented. This will allow all of the API calls to fail.
> [Fix] Set native payment to null for Android for now until feature is complete

- Assets/Editor/BuildPipeline/iOSTestPostProcessor.cs
- scripts/generator/graphql_generator/csharp/Editor/BuildPipeline/iOSPostProcessor.cs.erb
When we moved the Plugins folder from the top level to below Shopify/ there were a couple of paths that weren't updated in the iOS post processing scripts that caused the iOS test project export to fail.
> [Fix] Missed a couple of paths from Plugins folder move that caused iOS tests to fail

- BUILDTARGETS.md
With the changes to pulling in dependencies using the PlayServicesResolver, we no longer require developers to use Gradle as their build method.
> [Docs] Removes Gradle requirement for building Android APKs

- Assets/Shopify/Unity/Static/Editor/Resources/shopify_onboarding_illustration.png.meta
This image is in monocolor in unity 5.3, this changes an import setting that lets it work across versions
> Set 16 bit color for illustration

- .travis.yml
- android/shopify_buy_plugin/src/androidTest/java/com/shopify/unity/buy/models/MailingAddressInputTest.java
- android/shopify_buy_plugin/src/main/java/com/shopify/unity/buy/models/MailingAddressInput.java
Comparing string output of the Android JSON library is not a good idea since the ordering of properties is not guaranteed (which is expected but annoying). This patch modifies the class to allow being built from a JSON string so in the test we can reconstruct the object to do assertions on the properties. Also fixes an issue on Travis not accepting the latest build tools because we're using version 26 now.
> [Fix] Fix CI issues for Android tests

- scripts/generator/graphql_generator/csharp.rb
Fixes C# type generation after schema change on server side.
> Use C# "decimal" type for GraphQL "Decimal" one

- android/shopify_buy_plugin/build.gradle
Automatically extracts and copies any non-Google JAR or AAR dependency into the libs folder whenever `build_android.sh` is run.
> Add non-Google dependencies to libs folder

- Assets/Shopify/Plugins/iOS/Shopify/ApplePayButtonGenerator.h
- Assets/Shopify/Plugins/iOS/Shopify/ApplePayButtonGenerator.h.meta
- Assets/Shopify/Plugins/iOS/Shopify/ApplePayButtonGenerator.mm
- Assets/Shopify/Plugins/iOS/Shopify/ApplePayButtonGenerator.mm.meta
- scripts/generator/graphql_generator/csharp.rb
- scripts/generator/graphql_generator/csharp/Editor/BuildPipeline/iOSPostProcessor.cs.erb
- scripts/generator/graphql_generator/csharp/UI/ApplePayButtonUI.cs.erb
- scripts/generator/graphql_generator/csharp/UI/NativePayButtonUI.cs.erb
- scripts/test_iOS.sh
Adds a `NativePayButtonUI` script and associated native plugin code for IOS to generate the Apple Pay button from system frameworks.
> [Feature] Native Pay Button UI/Script for iOS

- Assets/Shopify/UIToolkit.meta
- Assets/Shopify/UIToolkit/Test.meta
- Assets/Shopify/UIToolkit/Test/Integration.meta
- Assets/Shopify/UIToolkit/Test/Integration/TestSanity.cs
- Assets/Shopify/UIToolkit/Test/Integration/TestSanity.cs.meta
- Assets/Shopify/UIToolkit/Test/Integration/UIToolkitIntegrationTests.unity
- Assets/Shopify/UIToolkit/Test/Integration/UIToolkitIntegrationTests.unity.meta
- Assets/Shopify/UIToolkit/Test/Unit.meta
- Assets/Shopify/UIToolkit/Test/Unit/Editor.meta
- Assets/Shopify/UIToolkit/Test/Unit/Editor/TestSanity.cs
- Assets/Shopify/UIToolkit/Test/Unit/Editor/TestSanity.cs.meta
Adds some future-disposable sanity tests into the folder structure I want to use for the UI Toolkit project. This wont be packaged into the unitypackage just yet and I double checked that unity is running the tests that I care about in ci.
> Create sanity checks + folder structure for UI Toolkit

- Assets/Editor/TestUnityEditorLoader.cs
- Assets/Editor/TestUnityEditorLoader.cs.meta
- scripts/generator/graphql_generator/csharp.rb
- scripts/generator/graphql_generator/csharp/SDK/Editor/UnityEditorLoader.cs.erb
This is a loader class that handles loading when the normal game loop is
not active. It binds to the EditorApplication.update event and manually
ticks the www coroutine forward to complete the request.
This is important because if we want more robust, smart editors we need a way to query the API from a custom editor within unity.
> Create Unity Editor Loader

- Gemfile
- Gemfile.lock
- dev.yml
This adds a dev.yml and a gemfile which helps shopify employees
configure their environment faster. It is not required and won't affect
anything if you are not a shopify employee and don't have dev installed.
> Adds dev configuration file for shopify employees

- scripts/generator/graphql_generator/csharp/SDK/WebCheckoutMessageReceiver.cs.erb
Fixes https://github.com/Shopify/unity-buy-sdk/issues/364
> [Fix] Destroy web checkout message receiver after we've successfully completed a checkout

- Assets/Shopify/UIToolkit/Themes/SingleProductTheme.cs
- Assets/Shopify/UIToolkit/Themes/SingleProductTheme.cs.meta
Provides the scaffolding and docs for a single product theme
avoiding the binding methods right now because they depend on the theme controllers being around.
> [UI Toolkit] Scaffold Single Product Theme

- Assets/Editor/MockLoaderProducts.cs
- Assets/Editor/TestShopify.cs
- Assets/Editor/TestUnityEditorLoader.cs
- Assets/IntegrationTests/TestUnityLoader.cs
- Assets/NativeTesting/iOS/ApplePayFlowTester.cs
- Assets/Shopify/Examples/Scripts/Helpers/ShopifyHelper.cs
- scripts/generator/graphql_generator/csharp/SDK/DefaultProductQueries.cs.erb
- scripts/generator/graphql_generator/csharp/SDK/DefaultQueries.cs.erb
- scripts/generator/graphql_generator/csharp/SDK/Delegates.cs.erb
- scripts/generator/graphql_generator/csharp/SDK/WebCheckoutMessageReceiver.cs.erb
- scripts/generator/graphql_generator/csharp/ShopifyBuy.cs.erb
This PR does the following:
+ Forces pagination. You can no longer load all products
+ Drops the maximum amount of products loaded per page to 20 (this arbitrary and I wonder if we should think about it more)
+ Forces the user to make callbacks that accept `after` eg. `(products, errors, after)`
+ `after` will be `null` if there are no more pages
> Product pagination

- Assets/Shopify/UIToolkit/Components/HTTPUtils.cs
- Assets/Shopify/UIToolkit/Components/HTTPUtils.cs.meta
- Assets/Shopify/UIToolkit/Components/RemoteImageLoader.cs
- Assets/Shopify/UIToolkit/Components/WebImageCache.cs
- Assets/Shopify/UIToolkit/Test/Integration/TestRemoteImageLoaderIntegration.cs
- Assets/Shopify/UIToolkit/Test/Integration/TestWebImageCacheIntegration.cs
- Assets/Shopify/UIToolkit/Test/Unit/Editor/TestHTTPUtils.cs
- Assets/Shopify/UIToolkit/Test/Unit/Editor/TestHTTPUtils.cs.meta
- Assets/Shopify/UIToolkit/Test/Unit/Editor/TestWebImageCache.cs
* Adds boolean flag `UseCache` to `RemoteImageLoader` to cache
downloaded images into the shared WebImageCache instance.
* Images downloaded are cached alongside their "Last Modified" timestamp
to prevent re-downloads of cached data and cache invalidation when they
are updated on the API side.
> Adds UseCache flag to RemoteImageLoader

- Assets/Shopify/UIToolkit/Test/Unit/Editor/TestSingleProductThemeController.cs
- Assets/Shopify/UIToolkit/Theme Controllers/SingleProductThemeController.cs
- scripts/generator/graphql_generator/csharp/type_response.cs.erb
When you load a node by id that doesn't exist, shopify returns `null` in
the response. This skips the null nodes which returns a normal looking
empty list in the query result.
> [Fix] Fixes bug where npe occurs when loading a node that doesn't exist

- Assets/Shopify/UIToolkit/Test/Unit/Editor/TestSingleProductThemeControllerEditor.cs
- Assets/Shopify/UIToolkit/Test/Unit/Editor/TestSingleProductThemeControllerEditor.cs.meta
- Assets/Shopify/UIToolkit/Theme Controllers/Editor/SingleProductThemeControllerEditor.cs
- Assets/Shopify/UIToolkit/Theme Controllers/Editor/SingleProductThemeControllerEditorView.cs
- Assets/Shopify/UIToolkit/Theme Controllers/Editor/SingleProductThemeControllerEditorView.cs.meta
- Assets/Shopify/Unity/SDK/GlobalGameObject.cs
Separates the view layer from the editor layer in the single product
editor, which allows us to mock the calls to EditorGUI and effectively
test states that the editor is rendering.
This view layer also implements an interface, which allows us to mock the behaviour in the tests and avoid calling EditorGUI functions, which would crash the scripts because they are being called outside of the normal editor inspector rendering flow.
> [UI Toolkit] Single product editor testing

- EXAMPLES.md
We can just directly link to the custom queries section, related https://github.com/Shopify/unity-buy-sdk/issues/414
> link custom queries

- EXAMPLES.md
Fixes the Build A Cart example by updating: 
1. after pagination
2. Variant names
3. Order of AddOrUpdate params
Related: https://github.com/Shopify/unity-buy-sdk/issues/414
cc @mikkoh
> fix build a cart example

- EXAMPLES.md
Fixes more issues with EXAMPLES.md:
1. Comments were still saying 'loads all', changing to mention it's just one page
2. Made query on second product page actually pass after
3. Updated cart options to consistently use customAttributes name
related https://github.com/Shopify/unity-buy-sdk/issues/414
cc @mikkoh
> fix example comments, variables names

- Assets/Editor/Publishing.cs
- scripts/publish.sh
Includes configurations so that we only package directories included in
the whitelist, as well as the ability to package files from the editor.
> Publish unitypackage from the editor

- Assets/Shopify/UIToolkit/Themes/IThemeBase.cs
- Assets/Shopify/Unity/ShopifyError.cs
related: https://github.com/Shopify/unity-buy-sdk/issues/414#issuecomment-352101457
Moves ShopifyError up from Shopify.Unity.SDK to Shopify.Unity namespace.
> move ShopifyError up from SDK

- Assets/Shopify/Unity/SDK/CartLineItems.cs
Adds doc block docs to `CartLineItem`. Fixes the part of #414 where
> Need to add DocBlock comments on CartLineItem
> Added doc block comments for CartLineItem

- EXAMPLES.md
This PR fixes #414's
> Example "Cart line items based on selected options" does not implement pagination using after
Also I see that:
> For Cart line items based on selected options. When copying pasting example we get an error stating "NoMatchingVariantException: Could not AddOrUpdate line item as no matching variant could be found for selected options". This is because there is no white option anymore
Was fixed in another PR but I feel that example shouldn't include two different ways of adding line items so I deleted it.
> Add an item based on selected options

- README.md
For #414:
> Maybe "Example Code Snippets" should be higher in the `README.md` file
I'd say for developers code snippets is actually the most important thing when it comes to docs.
> Moved code snippets higher up in the docs

- EXAMPLES.md
Went through all the EXAMPLES.md, except for the Native Pay section, and found a few small issues. 
First change is because the compiler picks the wrong overload when the page size is not given.
Second change is just a missing after.
Checked on:
> fix pagination in examples

- Assets/Shopify/UIToolkit/Components/VariantSelector.cs
- Assets/Shopify/UIToolkit/Components/VariantSelector.cs.meta
- Assets/Shopify/UIToolkit/Test/Unit/Editor/TestVariantSelector.cs
- Assets/Shopify/UIToolkit/Test/Unit/Editor/TestVariantSelector.cs.meta
ProductVariants on a product give us a set of selectable options but doesn't do a good job of seperating those options. For some of the UI we're looking to build for the UI Toolkit, we'll want to be able to select options independently of options. For example, select the Color of the shirt, then select the Size. This PR adds a class named `VariantOptionLookup` that takes in the variants on Product and builds an initial list of SelectionOptions to choose from. Once a user selects an option, you can pass this option back into the lookup class to get a set of the next selectable options.
> Variant/Selection Option Lookups

- Assets/Editor/Publishing.cs
- scripts/publish.sh
The first element of System.Environment.GetCommandLineArgs() is the executable itself, so running publish resulted in a borked install of unity because its internal executable was just a silly gzipped file
> Dont overwrite unity executable with unitypackage on publish

- Assets/Shopify/Plugins/Editor/ShopifyDependencies.xml
https://github.com/Shopify/unity-buy-sdk/issues/418
Removes the dependency so GooglePlayServicesResolver doesn't fetch Wallet Services. The meta tag is removed as it's part of the game-buy-android-sdk library.
> [Fix] Removed Wallet services from Google Resolver dependencies

- scripts/generator/graphql_generator/csharp.rb
- scripts/generator/graphql_generator/csharp/type.cs.erb
This fixes the build
Generated fields with a multi line deprecation reason would not be
properly commented out in the output, and would overflow causing syntax
errors in the log output. this pr adds the comments, and escapes the
strings when putting them in the docs.
> Fix multi line deprecation reason breaking code generation

- Assets/Shopify/UIToolkit/Test/Unit/Editor/TestBaseThemeControllerEditor.cs
- Assets/Shopify/UIToolkit/Theme Controllers/Editor/BaseThemeControllerEditor.cs
- Assets/Shopify/UIToolkit/Theme Controllers/ThemeControllerBase.cs
Unity does not serialize references to interfaces, so while the ref persisted after it was assigned, transitioning to a state where the ref was loaded from the serialized data would result in the Theme being null in the controller. This change lazily caches a ref to the theme so that it will always work no matter the situation. 
It maintains the `set Theme` accessor to be robust when we need to do dependency injection, which is especially useful in the tests.
> [UI Toolkit] Lazily fetch theme ref because unity wont serialize the ref

- Assets/Shopify/UIToolkit/Themes/Generic/Generic Single Product Theme Landscape.prefab
- Assets/Shopify/UIToolkit/Themes/Generic/Generic Single Product Theme Landscape.prefab.meta
Applies a max size to the card that shows up, making it not blown out on big screens and keeping it with some padding in smaller screens. It also fixes the product images so that the active one is always square and the previews are always beneath it properly.
> Fixes layout problems with gen single product shop theme

- Assets/Shopify/UIToolkit/ShopControllers/SingleProductShopController.cs
- Assets/Shopify/UIToolkit/Shops/Debug/DebugSingleProductShop.cs
- Assets/Shopify/UIToolkit/Shops/Generic/Classes/GenericMultiProductShop.cs
- Assets/Shopify/UIToolkit/Shops/Generic/Classes/GenericSingleProductShop.cs
- Assets/Shopify/UIToolkit/Shops/Interfaces/IMultiProductShop.cs
- Assets/Shopify/UIToolkit/Shops/Interfaces/ISingleProductShop.cs
- Assets/Shopify/UIToolkit/Test/Unit/Editor/TestSingleProductShopController.cs
We are moving towards not handling view concerns from our theme
controllers, so the interface from theme controller to theme only
requires the data that drives the theme. This reduces the interface
surface of the shop theme significantly.
> [UI Toolkit] Remove View Oriented callbacks from shop theme

- Assets/Shopify/UIToolkit/Editor/ProductPicker.cs
- Assets/Shopify/UIToolkit/ShopControllers/Editor/ShopControllerBaseEditor.cs
- Assets/Shopify/UIToolkit/ShopControllers/Editor/SingleProductShopControllerEditor.cs
Forces a repaint when the credentials verifier or the product picker
finished loading and updates the state of the editor. This fixes a bug
where some movement/UI event is required to show the state changes.
> [UI Toolkit] Force repaint in shop controller editor when state changes

- Assets/Shopify/UIToolkit/Components/ViewSwitcher.meta
- Assets/Shopify/UIToolkit/Components/ViewSwitcher/View Switcher Example.prefab
- Assets/Shopify/UIToolkit/Components/ViewSwitcher/View Switcher Example.prefab.meta
- Assets/Shopify/UIToolkit/Components/ViewSwitcher/ViewSwitcher.cs
- Assets/Shopify/UIToolkit/Components/ViewSwitcher/ViewSwitcher.cs.meta
- Assets/Shopify/UIToolkit/Test/Integration/TestViewSwitcher.cs
- Assets/Shopify/UIToolkit/Test/Integration/TestViewSwitcher.cs.meta
Allows pushing new views and maintaining a stack of views so that
navigating "back" always does the expected action. This will be used to
manage cart/product list/product details views in the Unity SDK factory
shops, and is designed to be easy to understand so that a 3rd party dev
can use it to build their own custom shops.
> View management

- Assets/Editor/TestCart.cs
- Assets/Shopify/UIToolkit/ShopControllers/Classes/CartController.cs
- Assets/Shopify/UIToolkit/ShopControllers/Classes/CartController.cs.meta
- Assets/Shopify/Unity/CartState.cs
- Assets/Shopify/Unity/SDK/CartLineItems.cs
- Assets/Shopify/Unity/SDK/Delegates.cs
This PR refactors event handling on cart line items. One controversial thing is that when `Reset` is called an event will be fired per item being removed from the line items list.
> UI CartLineItems Propagate Events

- Assets/Shopify/UIToolkit/Shops/Generic/Classes/GenericMultiProductShop.cs
- Assets/Shopify/UIToolkit/Shops/Generic/Classes/GenericSingleProductShop.cs
- Assets/Shopify/UIToolkit/Shops/Generic/Classes/MultiProductListItem.cs
- Assets/Shopify/UIToolkit/Shops/Generic/Classes/ProductDetailsView.cs
- Assets/Shopify/UIToolkit/Shops/Generic/Classes/ProductDetailsViewBindings.cs
- Assets/Shopify/UIToolkit/Shops/Generic/Classes/ProductDetailsViewBindings.cs.meta
- Assets/Shopify/UIToolkit/Shops/Generic/Classes/ProductListView.cs
- Assets/Shopify/UIToolkit/Shops/Generic/Prefabs/Generic Multi Product Shop Landscape.prefab
- Assets/Shopify/UIToolkit/Shops/Generic/Prefabs/Generic Single Product Shop Landscape.prefab
- Assets/Shopify/UIToolkit/Shops/Generic/Views/Product Details.prefab
- Assets/Shopify/UIToolkit/Shops/Generic/Views/Product Details.prefab.meta
- Assets/Shopify/UIToolkit/Shops/Generic/Views/Product List.prefab
Refactors @sleroux's work on the single product shop into an object that can be reused in the single product shop and the multi product shop's view layers for displaying product details.
The first commit is the feature itself, and could be merged as is. The second commit is the minimum amount of work I had to do to demo the feature.
> [UI Toolkit] Product Details in multi product shop

- Assets/Shopify/UIToolkit/Components/ProductCache.cs
- Assets/Shopify/UIToolkit/ShopControllers/MultiProductShopController.cs
- Assets/Shopify/UIToolkit/Shops/Generic/Classes/GenericMultiProductShop.cs
- Assets/Shopify/UIToolkit/Test/Unit/Editor/TestProductCache.cs
Splitting this off from my main infinite pagination PR. 
Adds a method to the `MultiProductShopController` which exposes triggering fetching more products. Handles dealing with storing the cursor and eventually setting `allProductsLoaded` to prevent more network calls once the entire product list is loaded. 
The `ProductListView` inherits from `GenericMultiProductShopView` which has a reference to the  `IGenericMultiProductShop` which, in turn, has a reference to `MultiProductShopController`, so adding a method in order to delegate.
> add load more to multi product

- Assets/Shopify/UIToolkit/ShopControllers/BaseShopController.cs
- Assets/Shopify/UIToolkit/ShopControllers/Classes/CartController.cs
- Assets/Shopify/UIToolkit/ShopControllers/Editor/ShopControllerBaseEditor.cs
- Assets/Shopify/UIToolkit/Shops/Generic/Classes/CartView.cs
- Assets/Shopify/UIToolkit/Shops/Generic/Classes/GenericMultiProductShop.cs
- Assets/Shopify/UIToolkit/Shops/Generic/Views/Cart Panel.prefab
- Assets/Shopify/UIToolkit/Test/Unit/Editor/TestBaseShopControllerEditor.cs
Small PR that connects the buttons to the `StartPurchase` method in the CartController. I've also abstracted the NativePayKey into a property that lives on the ShopController and can be edited from the editor.
Instead of exposing a 'Native Pay Key' which seems pretty ambigious I've exposed a 'Apple Merchant ID' field for Apple Pay instead. When Android Pay is supported we can add another optional field named Android Key or something. This way it's a lot more clear.
> Connected checkout methods to Cart Panel and added Apple Merchant ID to base controller

- Assets/Shopify/Plugins/iOS/Shopify/ApplePayButtonGenerator.h
- Assets/Shopify/Plugins/iOS/Shopify/ApplePayButtonGenerator.mm
- Assets/Shopify/UIToolkit/ShopControllers/Classes/CartController.cs
- Assets/Shopify/UIToolkit/Shops/Generic/Classes/CartView.cs
- Assets/Shopify/UIToolkit/Shops/Generic/Classes/GenericMultiProductShop.cs
- Assets/Shopify/UIToolkit/Shops/Generic/Views/Cart Panel.prefab
- Assets/Shopify/Unity/UI/NativePayButtonUI.cs
- ios-build/Unity-iPhone/shoppingdemo.entitlements
Adds `CanCheckoutWithNativePay` call to the Shop so the CartView can query when to show the Apple Pay button. As I was testing this patch I noticed the minimum spacing flag on the `NativePayButtonUI` script was causing problems and had an bug in it's method signature so I've decided to remove it since it's kind of pointless anyways. It wasn't clear why it existed and make it so the size of the button the developer sees in Unity matches the one rendered on iOS.
> Updated Cart Panel to enable Apple Pay checkouts

- Assets/Shopify/Unity/SDK/WebCheckoutMessageReceiver.cs
- scripts/generator/graphql_generator/csharp/SDK/WebCheckoutMessageReceiver.cs.erb
Adds the same destroy logic we had after a success callback for when cancel gets fired so we never get cancelled fired twice.
Note: After this lands into master I'll do the hotfix release from the v0.4.1 tag
> [Hotfix] Destroy message receiver after the checkout was cancelled so we don't get any callbacks

- Assets/Shopify/Plugins/iOS/Shopify/ApplePayEventResponse.swift
- Assets/Shopify/Plugins/iOS/Shopify/BuyTests/ApplePayErrorDeserializingTests.swift
- Assets/Shopify/Plugins/iOS/Shopify/BuyTests/ApplePayFlowTests.swift
- Assets/Shopify/Plugins/iOS/Shopify/BuyTests/Models/Models.swift
- Assets/Shopify/Plugins/iOS/Shopify/BuyTests/StringTests.swift
- Assets/Shopify/Plugins/iOS/Shopify/Deserializable/PKPaymentSummaryItem+Deserializable.swift
- Assets/Shopify/Plugins/iOS/Shopify/Deserializable/PKShippingMethod+Deserializable.swift
- Assets/Shopify/Plugins/iOS/Shopify/String/PKPaymentAuthorizationStatus+String.swift
- Assets/Shopify/Plugins/iOS/Shopify/String/PKPaymentSummaryItemType+String.swift
- Assets/Shopify/UIToolkit/ShopControllers/BaseShopController.cs
- Assets/Shopify/UIToolkit/ShopControllers/Classes/CartController.cs
- Assets/Shopify/UIToolkit/Shops/Generic/Classes/CartView.cs
- Assets/Shopify/Unity/Cart.cs
- Assets/Shopify/Unity/Editor/BuildPipeline/iOSPostProcessor.cs
- Assets/Shopify/Unity/UI/NativePayButtonUI.cs
* Xcode 9.3 beta makes the `PKPayment*` enum types actually inherit from `RawRepresentable` thus causing a redefinition conflict with `rawValue`. Since we parse it from a string I've added a `rawStringValue` init method to most types to keep the functionality the same
* Cleaned up some unused code path warnings caused by switching between platforms
* Fixed an annoying issue in our integration tests where the standard/expedited shipping costs we changed to be rounded numbers.
> Xcode 9.3 beta support and warning cleanup

- Assets/Editor/MockLoaderProducts.cs
- Assets/IntegrationTests/TestShopifyProducts.cs
- Assets/IntegrationTests/Utils.cs
- Assets/Shopify/Examples/Scripts/Panels/ProductsPanelCell.cs
- Assets/Shopify/Unity/SDK/DefaultCollectionQueries.cs
- Assets/Shopify/Unity/SDK/DefaultProductQueries.cs
- Assets/Shopify/Unity/ShopifyBuy.cs
For loading different image resolutions, we were sending aliased `image` fields to the Storefront API and relying on the Image's `src` property for the sized URL. Using `src` directly has now been deprecated and `transformedSrc` should be used instead.
`transformedSrc` now takes in an alias to be used so instead of having a query that looks like this:
```graphql
image___pico: image(maxWidth: 16, maxHeight: 16) {
altText
transformedSrc
}
image___icon: image(maxWidth: 32, maxHeight: 32) {
altText
transformedSrc
}
```
Querying for different image sizes looks like this:
```graphql
image {
altText
transformedSrc
transformedSrc___pico: transformedSrc(maxWidth: 16, maxHeight: 16)
transformedSrc___icon: transformedSrc(maxWidth: 32, maxHeight: 32)
}
```
This means the client side API has changed …
> Use image aliases for transformedSrc properties instead of image queries

- Assets/IntegrationTests/TestGlobalGameObject.cs
- Assets/IntegrationTests/TestGlobalGameObject.cs.meta
- Assets/Scenes/IntegrationTestBlankScene.unity
- Assets/Scenes/IntegrationTestBlankScene.unity.meta
- Assets/Shopify/Unity/SDK/GlobalGameObject.cs
- ProjectSettings/EditorBuildSettings.asset
* Prevent `GlobalGameObject` from being destroyed whenever a new scene is loaded in.
> Dont destroy global game object when loading new scenes

- scripts/generator/graphql_generator/csharp.rb
Fixes https://github.com/Shopify/unity-buy-sdk/issues/533
When generating the `CurrencyCode` field for `MoneyInput`, we were generating a nullable cast which doesn't compile since `CurrencyCode` is an enum type. The reason this was happening was because we were not passing down the `is_non_null` flag to recursive calls in `graph_type_to_csharp_cast`. This fix passes the flag down so we can properly recognize non-null types.
> Fixed bug in GraphQL generator that never passed non_null information to recursive call

- scripts/generator/graphql_generator/csharp.rb
- scripts/generator/graphql_generator/csharp/type.cs.erb
- scripts/generator/graphql_generator/csharp/type_response.cs.erb
Fixes https://github.com/Shopify/unity-buy-sdk/issues/537
The Storefront API introduced `PricingValue` which is the first UNION GraphQL type to be used in the API. We didnt have a way of handling UNION types so this PR adds that functionality to the generator. The approach here is to do a similiar thing we do for interfaces since a union is just a GraphQL interface that has no shared members. The main code difference is that since unions dont have any fields, the field generation code is omitted.
> Added GraphQL UNION type generation support

- Assets/Shopify/UIToolkit/Test/Unit/Editor/TestBaseShopControllerEditor.cs
- Assets/Shopify/UIToolkit/Test/Unit/Editor/TestShopControllerBase.cs
- Assets/Shopify/UIToolkit/Test/Unit/Editor/TestSingleProductShopController.cs
- Assets/Shopify/UIToolkit/Test/Unit/Editor/TestSingleProductShopControllerEditor.cs
- Assets/Shopify/Unity/SDK/Editor/UnityEditorLoader.cs
Fixes https://github.com/Shopify/unity-buy-sdk/issues/535
Some of our Edit Mode tests for the UIToolkit were failing because we were calling `DontDestroyOnLoad` from the `GlobalGameObject` which can only be called during Play Mode tests. This PR replaces any calls to adding components to the `GlobalGameObject` to a locally-created GameObject instead to avoid this call. In cases where we query the network, since `UnityLoader` touches the `GlobalGameObject` I've replaced the loader with a `UnityEditorLoader` which is an editor-safe network client.
> Fixes DontDestroyOnLoad error for Edit Mode UIToolkit tests

- scripts/common.sh
https://github.com/Shopify/unity-buy-sdk/issues/521
Allow overriding of UNITY_APP_PATH environment variable to allow users to pass in installations from Unity Hub or other sources. Default is still set to point to `/Applications/Unity/Unity.app` in case your not using Hub or an older version of Unity.
> Override UNITY_APP_PATH with custom Unity path

- .travis.yml
- Assets/Editor/BuildPipeline/iOSTestPostProcessor.cs
- Assets/Shopify/Plugins/iOS/Shopify/BuyTests/ApplePayErrorDeserializingTests.swift
- Assets/Shopify/Plugins/iOS/Shopify/BuyTests/ApplePayFlowTests.swift
- Assets/Shopify/Plugins/iOS/Shopify/BuyTests/Models/Models.swift
- Assets/Shopify/Plugins/iOS/Shopify/Cart+ApplePay.swift
- Assets/Shopify/Plugins/iOS/Shopify/Deserializable/Deserializable.swift.meta
- Assets/Shopify/Plugins/iOS/Shopify/Deserializable/PKPaymentSummaryItem+Deserializable.swift
- Assets/Shopify/Plugins/iOS/Shopify/Deserializable/PKPaymentSummaryItem+Deserializable.swift.meta
- Assets/Shopify/Plugins/iOS/Shopify/Deserializable/PKShippingMethod+Deserializable.swift.meta
- Assets/Shopify/Plugins/iOS/Shopify/MessageCenter.swift
- Assets/Shopify/Plugins/iOS/Shopify/PaymentAuthorizationControlling/PaymentAuthorizationControlling.swift
- Assets/Shopify/Plugins/iOS/Shopify/PaymentSession.swift
- Assets/Shopify/Plugins/iOS/Shopify/UnityMessage.swift
- Assets/Shopify/Plugins/iOS/Shopify/WebCheckoutSession.swift
- Assets/Shopify/Unity/Editor/BuildPipeline/iOSPostProcessor.cs
Migrates the iOS plugin to support Swift 4 and resolves any errors that were caused from the switch. The two key errors that were happening were:
1. Illegal overriding of a Swift extension method in Deserializable. Fixed this by added in `@objc` prefix to make it into an ObjC extension instead.
2. Failable initializer not captured in `PaymentAuthorizationController` protocol. The `PaymentAuthorizationViewController` framework class has a failable initializer and since it implements this protocol the protocol method definition should match.
> Migrate iOS plugin to Swift 4

- scripts/generator/graphql_generator/csharp/type_response.cs.erb
Before
```
/// <summary>
/// Represents information about the metafields associated to the specified resource.
/// </summary>
public interface HasMetafields {
/// <summary>
/// The metafield associated with the resource.
/// </summary>
/// <param name="alias">
/// If the original field queried was queried using an alias, then pass the matching string.
/// </param>
Metafield metafield();
/// <summary>
/// A paginated list of metafields associated with the resource.
/// </summary>
/// <param name="alias">
/// If the original field queried was queried using an alias, then pass the matching string.
/// </param>
MetafieldConnection metafields();
}
```
After:
```
/// <summary>
/// Represents information about the metafields associated to the specified resource.
/// </summary>
public interface …
```
> Fix the generator for interfaces

- Assets/Editor/TestDefaultCheckoutQueries.cs
- Assets/Shopify/Unity/SDK/DefaultCheckoutQueries.cs
- Assets/Shopify/Unity/SDK/iOS/iOSNativeCheckout.ApplePayEventReceiver.cs
- Assets/Shopify/Unity/SDK/iOS/iOSNativeCheckout.cs
This is fix for some failing ios test specific tests. 
Please see this PR for some context: https://github.com/Shopify/unity-buy-sdk/pull/580
The failing tests were:
> ApplePayFlowTests.testCompleteInvalidBillingAddressCheckout()
> 	ApplePayFlowTests.testCompleteInvalidShippingAddressCheckout()
> 	ApplePayFlowTests.testCompleteInvalidShippingAddressCheckoutIos11()
> 	ApplePayFlowTests.testCompleteInvalidShippingContactCheckout()
> 	ApplePayFlowTests.testCompleteSuccessfulCheckout()
> 	ApplePayFlowTests.testSelectShippingMethod()
> 	ApplePayFlowTests.testSetInvalidShippingContact()
> 	ApplePayFlowTests.testSetInvalidShippingContactIos11()
> 	ApplePayFlowTests.testSetShippingContact()
> Fix ApplePay flow test failures

- Assets/Editor/TestDefaultCheckoutQueries.cs
**Issue**: A change happened in the storefront API which causes the order of the return fields in `CheckoutCompleteWithTokenizedPaymentV2` mutation to change. 
**Impact**: CI test specifically `Shopify.Tests.TestDefaultCheckoutQueries.TestCheckoutCompleteWithTokenizedPaymentV2` fails. 
**Summary of change** 
- When a failure happens on `TestCheckoutCompleteWithTokenizedPaymentV2`, print out the full mutation's response as well as the default printout (delta between expected and actual response).
- _Reorder_ the payment `type` field in the expected response (a hard coded string)
> Fix build failure

- Assets/Shopify/Unity/Editor/BuildPipeline/ExtendedPBXProject.cs
- Assets/Shopify/Unity/Editor/BuildPipeline/iOSPostProcessor.cs
Adds -all_load linker flag to load in all symbols required from the new iOS static library on release builds.
> Added -all_load linker flag to UnityFramework for static linking symbols

- PluginDependencies/iOSPlugin/UnityBuySDKPlugin.xcodeproj/project.pbxproj
Resolves https://github.com/Shopify/unity-buy-sdk/issues/611.
Archiving release builds using the Unity SDK cause errors when trying to build with a bitcode enabled build (this is enabled by default). This fix enables bitcode generation for the new static library target we use for the iOS native plugin.
> Embed bitcode for iOS static lib target

- .github/workflows/build.yml
- .github/workflows/test.yml
Temporarily removing the publish step from our build action due to security concerns around the MirrorNG/unity-runner account on Github.
> Removed final publish action that uses MirrorNG/unity-runner due to security concerns
