- CONTRIBUTING.md
- README.md
Added contribution links to readme, and fixed examples anchor point
> [FIX] Added updated contribution info to README

- circle.yml
- scripts/install_unity.sh
- Downloads the iOS editor support for Unity and installs it on CI
- Adds some more debugging information to determine which version of Unity is being downloaded
> [Feature] iOS Editor Support for CI

- Assets/Plugins/iOS/Shopify/BuyTests/Models/Models.swift
- Assets/Plugins/iOS/Shopify/BuyTests/SerializableTests.swift
- Moves conveniences into a Models struct. 
+ Allows these conveniences to be used in other tests further down the road
> [Refactor] Serialization tests

- README.md
The following PR adds deep links to different parts of the example documentation. This will allow developers to quickly find the portions of documentation they need easier.
> [FEATURE] Deep links to examples

- Assets/Plugins/iOS/Shopify/BuyTests/PaymentSessionTests.swift
- Assets/Plugins/iOS/Shopify/PaymentSession.swift
Renamed uppercase enums to lowercase
> [Fix] Renamed enum to follow conventions

- Assets/Plugins/iOS/Shopify/BuyTests/Models/Models.swift
> [Fix] Refactor models

- Assets/Editor/MockLoaderCheckouts.cs
- Assets/Editor/TestDefaultQueriesCheckout.cs
- scripts/generator/graphql_generator/csharp/SDK/DefaultQueriesCheckout.cs.erb
Adds various queries for mutations on shipping addresses, shipping line item, and email address
> [Feature] Checkouts shipping queries

- Assets/Plugins/iOS/Shopify/Unity-iPhone-Tests-Bridging-Header.h
- Adds missing Cart header import required for tests
> [Fix] iOS Test import 

- scripts/generator/graphql_generator/csharp/Cart.cs.erb
- Adds functionality to the Cart to set the Shipping and Email for the Checkout
- Adds Polling for Available shipping rates
> [Feature] Checkouts Shipping Mutations

- Assets/Editor/TestDefaultQueriesCheckout.cs
- scripts/generator/graphql_generator/csharp/SDK/DefaultQueriesCheckout.cs.erb
+ Adds Token Payment queries for creating a payment and polling to default queries
+ Adds tests
> [Feature] Checkouts Token Payment

- Assets/Editor/TestDefaultQueriesCheckout.cs
- scripts/generator/graphql_generator/csharp/SDK/DefaultQueriesCheckout.cs.erb
+ Adds Checkout with token queries
> [Feature] Checkouts payment

- scripts/generator/graphql_generator/csharp.rb
- scripts/generator/graphql_generator/csharp/Cart.cs.erb
- scripts/generator/graphql_generator/csharp/SDK/Delegates.cs.erb
- scripts/generator/graphql_generator/csharp/SDK/GlobalGameObject.cs.erb
- scripts/generator/graphql_generator/csharp/SDK/IWebCheckout.cs.erb
- scripts/generator/graphql_generator/csharp/SDK/iOS/iOSWebCheckout.cs.erb
First pass at implementing an interface and the basics of a web checkout implementor for iOS.
> [Unity] Add IWebPayable with Web Checkout API

- scripts/generator/graphql_generator/csharp/Cart.Poll.cs.erb
- scripts/generator/graphql_generator/csharp/Cart.cs.erb
+ These methods are private for now, till we finalize on how we handle talking to the `Cart` from an instance of `INativeCheckout`
> [Feature] Added the ability to checkout with token to cart

- scripts/generator/graphql_generator/csharp/Cart.cs.erb
- scripts/generator/graphql_generator/csharp/SDK/INativeCheckout.cs.erb
- scripts/generator/graphql_generator/csharp/SDK/iOS/iOSNativeCheckout.cs.erb
+ Renames methods in INativeCheckout to fit the IWebCheckout
+ Adds checks before using ICheckouts so it doesn't crash on non iOS platforms
<hr>
+ Will add in exceptions that are thrown in a later PR
> [Feature] INativeCheckout

- scripts/generator/graphql_generator/csharp.rb
- scripts/generator/graphql_generator/csharp/Cart.CheckoutAccessors.cs.erb
- scripts/generator/graphql_generator/csharp/Cart.Poll.cs.erb
- scripts/generator/graphql_generator/csharp/Cart.cs.erb
- scripts/generator/graphql_generator/csharp/SDK/Delegates.cs.erb
- scripts/generator/graphql_generator/csharp/SDK/NoCheckoutException.cs.erb
- scripts/generator/graphql_generator/csharp/SDK/NoQueryException.cs.erb
- scripts/generator/graphql_generator/csharp/SDK/iOS/iOSNativeCheckout.ApplePayEventReceiver.cs.erb
- scripts/generator/graphql_generator/csharp/SDK/iOS/iOSNativeCheckout.cs.erb
+ Added public accessors to cart
+ Moved Cart partial class to iOSNativeCheckout partial class
<hr>
+ Does not include tests for public methods, will add this later
> [Feature] Changed Checkout private mutators to public

- Assets/Plugins/iOS/Shopify/BuyTests/SerializableTests.swift
- Assets/Plugins/iOS/Shopify/Serializable/PKPayment+Serializable.swift
- Assets/Plugins/iOS/Shopify/Serializable/PKPaymentToken+Serializable.swift
- scripts/generator/graphql_generator/csharp.rb
- scripts/generator/graphql_generator/csharp/SDK/iOS/PaymentDeserializer.cs.erb
+ Adds deserialization for token data
+ Refactors serializable classes
> [Feature] Native checkout token deserialization

- Assets/UnityTestTools/NativeTesting/Native/NativeMessageTester.cs
- Assets/UnityTestTools/NativeTesting/iOS/ApplePayEventTester.cs
- scripts/generator/graphql_generator/csharp/SDK/NativeMessage.cs.erb
- scripts/generator/graphql_generator/csharp/SDK/Serializable.cs.erb
- scripts/generator/graphql_generator/csharp/SDK/iOS/ApplePayEventResponse.cs.erb
- scripts/generator/graphql_generator/csharp/SDK/iOS/ShippingMethod.cs.erb
- scripts/generator/graphql_generator/csharp/SDK/iOS/SummaryItem.cs.erb
* Replaces JsonUtility uses of Deserialize with MiniJSON
We can probably follow this up with a fancier generic-based implementation like JsonUtility does in the future.
> [Fix] Refactors JsonUtility to use MiniJSON

- scripts/generator/graphql_generator/csharp/SDK/Serializable.cs.erb
* Adds ToString override to Serializable
> [Fix] Adds ToString override to Serializable

- Assets/Editor/TestDefaultQueriesCheckout.cs
- scripts/generator/graphql_generator/csharp/Cart.Poll.cs.erb
- scripts/generator/graphql_generator/csharp/Cart.cs.erb
- scripts/generator/graphql_generator/csharp/SDK/DefaultQueriesCheckout.cs.erb
+ Splits the query for setting shipping address and retrieving shipping rates
+ That way we don't get a Graphql error when we first get an error setting shipping address field
> [Fix] Refactor checkout shipping query

- scripts/generator/graphql_generator/csharp/SDK/iOS/iOSWebCheckout.cs.erb
The joy of C#/iOS bridge development :)
> [Fixup] Fixes name of message sent when user hits thank you page

- Assets/Editor/TestResponseDeserialization.cs
- scripts/generator/graphql_generator/csharp/Cart.cs.erb
- scripts/generator/graphql_generator/csharp/SDK/ShopifyError.cs.erb
- scripts/generator/graphql_generator/csharp/SDK/iOS/iOSWebCheckout.cs.erb
- scripts/generator/update_schema
* Adds DidCheckoutCompleteSuccessfully method that checks the CurrentCart's completedAt date to see if it's not null.
* Updates DateTime customScalar in the generator to return a nullable type.
> [Feature] Adds checkout validation after navigating to end of a web checkout.

- scripts/generator/graphql_generator/csharp/Cart.cs.erb
+ added platform exceptions where there were TODOs
> [Fix] Added platform exception

- EXAMPLES.md
+ Updates example code to use `ShopifyError`
+ Fixes syntax error in sample code
+ Changed `billingAddress` query to `primaryDomain` query because it no longer exists in the schema
> [Fix] Callbacks for sample code

- scripts/generator/graphql_generator/csharp/Cart.cs.erb
Small patch to add a docstring to the new CheckoutWithNativeWebView method on Cart.cs
> [Docs] Adds docstring to public facing CheckoutWithNativeWebView method

- scripts/generator/graphql_generator/csharp/SDK/QueryLoader.cs.erb
+ Prints outgoing queries and their responses when compiled with `SHOPIFY_VERBOSE_DEBUG `
> [Feature] Test verbose debug

- Assets/Plugins/iOS/Shopify/BuyTests/ApplePayFlowTests.swift
- Assets/Plugins/iOS/Shopify/BuyTests/Mocks/MockPaymentToken.swift
- Assets/Plugins/iOS/Shopify/BuyTests/Models/Models.swift
+ Adds tests that test apple pay checkout for items with Shipping required
+ tests for items that don't require shipping
> [Feature] Complete Shipping Apple Pay Tests

- Assets/Editor/TestCart.cs
- scripts/generator/graphql_generator/csharp/Cart.cs.erb
Adds a `Reset` method on `Cart` that allows the cart to have it's state be reset and be reused.
> [Feature] Adds Reset method to Cart for clearing out state

- scripts/generator/graphql_generator/csharp.rb
- scripts/generator/graphql_generator/csharp/Cart.cs.erb
- scripts/generator/graphql_generator/csharp/SDK/DefaultQueries.cs.erb
- scripts/generator/graphql_generator/csharp/SDK/DefaultShopQueries.cs.erb
- scripts/generator/graphql_generator/csharp/SDK/Delegates.cs.erb
- scripts/generator/graphql_generator/csharp/SDK/INativeCheckout.cs.erb
- scripts/generator/graphql_generator/csharp/SDK/iOS/iOSNativeCheckout.cs.erb
- scripts/generator/graphql_generator/csharp/ShopifyBuy.cs.erb
Same as #199 except into Beta this time.
> [Fix] country code

- BUILDTARGETS.md
- EXAMPLES.md
- README.md
* Adds BUILDTARGETS.md talking about iOS requirements and build target post processing.
* Adds section to README.md pointing to BUILDTARGETS.md
> [Docs] Adds Supported build targets section to README.md and BUILDTARGETS.md doc file

- EXAMPLES.md
+ Fixed products to fit products on new unity-examples store
+ Added callback to CanCheckoutWithNativePay
> Fixed Examples.md

- EXAMPLES.md
This PR makes content edits to the new content at EXAMPLES.md in keeping with the current style guide and docs best practices. These changes will be made also to https://help.shopify.com/api/sdks/custom-storefront/unity-buy-sdk/getting-started (re: https://github.com/Shopify/documentation/issues/11309).
> Content edits for EXAMPLES.md

- Assets/Plugins/Android.meta
- Assets/Plugins/Android/mainTemplate.gradle
- Assets/Plugins/Android/mainTemplate.gradle.meta
- unity_buy_android/unity_buy_plugin/build.gradle
+ Added `mainTemplate.gradle` which is the gradle file that the Unity Android project will use
> [Feature] Added template Gradle and support library 

- Assets/Editor/iOS/TestWebCheckout.cs
- scripts/generator/graphql_generator/csharp.rb
- scripts/generator/graphql_generator/csharp/SDK/NativeWebViewMessageReceiver.cs.erb
- scripts/generator/graphql_generator/csharp/SDK/iOS/iOSWebCheckout.cs.erb
+ All of `iOSWebViewMessageReceiver` can be used for Android as well. Refactored to generalize it.
> Refactored iOSWebViewMessageReceiver to NativeWebViewMessageReceiver

- scripts/test_android.sh
- scripts/test_android_unit.sh
- unity_buy_android/checkstyle/config.xml
- unity_buy_android/checkstyle/suppressions.xml
- unity_buy_android/unity_buy_plugin/build.gradle
- unity_buy_android/unity_buy_plugin/src/main/java/com/shopify/unity/buy/UnityBuyPlugin.java
Copies over the checkstyle rules and task we use for other Shopify Android projects:
https://github.com/Shopify/mobile-shopify/wiki/Checkstyle
It's also worth adding this to Android Studio directly so you can run the rules as you develop:
https://github.com/Shopify/mobile-shopify/wiki/Checkstyle-in-Android-Studio
> [Quality] Adds checkstyle task to Android project

- scripts/generator/graphql_generator/csharp.rb
- scripts/generator/graphql_generator/csharp/Cart.cs.erb
- scripts/generator/graphql_generator/csharp/SDK/Android/AndroidWebCheckout.cs.erb
+ Adds implementation of Android Web Checkout to the managed code side
> [Feature] Added AndroidWebCheckout to Unity SDK

- Assets/Plugins/Android/mainTemplate.gradle
- android/shopify_buy_plugin/build.gradle
- android/shopify_buy_plugin/src/main/java/com/shopify/unity/buy/JsonSerializable.java
- android/shopify_buy_plugin/src/main/java/com/shopify/unity/buy/UnityMessage.java
- android/shopify_buy_plugin/src/test/java/com/shopify/unity/buy/UnityBuyPluginTest.java
- android/shopify_buy_plugin/src/test/java/com/shopify/unity/buy/UnityMessageTest.java
+ Adds a container class for Unity Messages that serializes content for Unity to consume
> [Feature] Android unity message

- android/shopify_buy_plugin/src/main/java/com/shopify/unity/buy/WebIntentFragment.java
- android/shopify_buy_plugin/src/main/java/com/shopify/unity/buy/WebIntentListener.java
+ Added a fragment that launches a `CustomTabs` intent for a URL
> [Feature] Added Android Web Intent Fragment

- android/shopify_buy_plugin/src/main/java/com/shopify/unity/buy/WebCheckoutSession.java
+ Adds the layer that Unity talks to, to launch a web intent with a checkout URL
> [Feature] Android web checkout session

- Assets/Editor/TestDefaultShopQueries.cs
- Assets/Editor/TestDefaultShopQueries.cs.meta
- scripts/generator/graphql_generator/csharp/SDK/DefaultShopQueries.cs.erb
+ Adds `acceptedCardBrands` and `supportedDigitalWallets` to default shop query
+ Adds tests
> [Feature] Added new Payment settings to default shop query

- scripts/check_setup.sh
+ Fixes an issue where the setup on machine is always False
+ changed `echo` to `printf` to use escape characters and fix lint-ing issues
> [Refactor] Check setup script

- android/shopify_buy_plugin/src/main/AndroidManifest.xml
- android/shopify_buy_plugin/src/main/java/com/shopify/unity/buy/AndroidPayCheckoutSession.java
- android/shopify_buy_plugin/src/main/java/com/shopify/unity/buy/MessageCenter.java
- android/shopify_buy_plugin/src/main/java/com/shopify/unity/buy/UnityAndroidPayFragment.java
- android/shopify_buy_plugin/src/main/java/com/shopify/unity/buy/UnityMessage.java
- android/shopify_buy_plugin/src/main/java/com/shopify/unity/buy/WebCheckoutSession.java
- android/shopify_buy_plugin/src/main/java/com/shopify/unity/buy/models/MailingAddressInput.java
- android/shopify_buy_plugin/src/main/java/com/shopify/unity/buy/utils/WalletErrorFormatter.java
- android/shopify_buy_plugin/src/test/java/com/shopify/unity/buy/UnityMessageTest.java
- scripts/generator/graphql_generator/csharp/SDK/Android/AndroidNativeCheckout.cs.erb
* Adds Google API client and wallet listeners to UnityAndroidPayFragment to launch a masked wallet request.
> [Android Pay] Launches wallet chooser UI when checking out using Native Pay from Unity

- Assets/Plugins/iOS/Shopify/BuyTests/SerializableTests.swift
- Assets/Plugins/iOS/Shopify/Deserializable/PKPaymentSummaryItem+Deserializable.swift
- Assets/Plugins/iOS/Shopify/Deserializable/PKShippingMethod+Deserializable.swift
- Assets/Plugins/iOS/Shopify/Serializable/PKContact+Serializable.swift
+ Moves enum field to extension, so that it is under the correct namespace.
+ Fixed #138
> [Refactor] iOS serialization enum

- BUILDDETAILS.md
- BUILDTARGETS.md
- EXAMPLES.md
- README.md
+ Documents Android Web Checkout feature in readme as Chrome Custom Tab
+ Fixes some doc linkings to be local
+ Documents Android build requirements
> [Fix] android web checkout docs

- android/shopify_buy_plugin/src/main/java/com/shopify/unity/buy/AndroidPayCheckoutSession.java
- android/shopify_buy_plugin/src/main/java/com/shopify/unity/buy/AndroidPaySessionCallback.java
- android/shopify_buy_plugin/src/main/java/com/shopify/unity/buy/AndroidPaySessionCallbacks.java
- android/shopify_buy_plugin/src/main/java/com/shopify/unity/buy/UnityAndroidPayFragment.java
Forgot to add in AndroidPaySessionCallbacks from previous PR 🤦‍♂️
> [Fix] Adds missing file from previous masked-wallet branch commit

- Assets/Plugins/iOS/Shopify/BuyTests/ApplePayFlowTests.swift
- Assets/UnityTestTools/NativeTesting/iOS/ApplePayFlowTester.cs
- scripts/generator/graphql_generator/csharp/Cart.cs.erb
- scripts/generator/graphql_generator/csharp/SDK/iOS/iOSNativeCheckout.cs.erb
+ Adds the store name as the last summary line item to fit Apple Pay design guidelines
+ Fixes #213
> [Feature] Apple pay store name total

- Assets/Editor/MockLoaderCheckouts.cs
- Assets/Editor/TestDefaultCheckoutQueries.cs
- scripts/generator/Gemfile
- scripts/generator/Gemfile.lock
~~Looks like the storefront API moved around a few params, fixing tests.~~
cc @Shopify/gaming
> update checkout query

- scripts/generator/graphql_generator/csharp/SDK/iOS/ApplePayEventResponse.cs.erb
- scripts/generator/graphql_generator/csharp/SDK/iOS/iOSNativeCheckout.ApplePayEventReceiver.cs.erb
+ Adds functionality to create ApplePayError based on the different UserErrors received
+ In cases where we receive an error that we don't expect or an error that can not be created into an ApplePayError we return a Failure.
> [Feature] Apple pay event response error

- scripts/generator/graphql_generator/csharp/SDK/CartLineItems.cs.erb
Breaking this change out from https://github.com/Shopify/unity-buy-sdk/pull/297#discussion_r135083135 where it will be cleaner to be able to access the variant directly.
> convert VariantIdFromSelectedOptions to VariantFromSelectedOptions

- scripts/generator/graphql_generator/csharp/SDK/iOS/iOSNativeCheckout.ApplePayEventReceiver.cs.erb
+ Adds error handling for an unserviceable shipping area
+ Fixes false positive success prior
> [Fix] Apple pay shipping unserviceable address

- Assets/Plugins/iOS/Shopify/ApplePayEventDispatcher.swift
- Assets/Plugins/iOS/Shopify/ApplePayEventResponse.swift
- Assets/Plugins/iOS/Shopify/PaymentSession+PaymentAuthorizationControllerDelegate.swift
- Assets/Plugins/iOS/Shopify/PaymentSession+PaymentAuthorizationViewControllerDelegate.swift
- Assets/Plugins/iOS/Shopify/PaymentSession.swift
+ Implements new `PaymentAuthorization` delegate methods 
+ Will be adding tests in a separate PR
> [Feature] iOS 11 authorization support

- Assets/Editor/MockLoaderCheckouts.cs
- Assets/Editor/TestCart.cs
- scripts/generator/graphql_generator/csharp/Cart.cs.erb
- scripts/generator/graphql_generator/csharp/CartState.cs.erb
- scripts/generator/graphql_generator/csharp/SDK/CartLineItems.cs.erb
Fixes https://github.com/Shopify/unity-buy-sdk/issues/148
Adds functionality for getting the cart subtotal. 
@Shopify/gaming
> add CartLineItems Subtotal

- Assets/Editor/TestShopify.cs
- scripts/generator/graphql_generator/csharp/ShopifyBuy.cs.erb
This PR adds publish destination to the version string.
> [Feature] Tracking publish destination

- .travis.yml
- Assets/Plugins/Android/AndroidManifest.xml
- android/shopify_buy_plugin/build.gradle
- android/shopify_buy_plugin/src/androidTest/java/com/shopify/unity/buy/AndroidPayCheckoutSessionTest.java
- android/shopify_buy_plugin/src/androidTest/java/com/shopify/unity/buy/WebIntentFragmentTest.java
- android/shopify_buy_plugin/src/main/AndroidManifest.xml
- android/shopify_buy_plugin/src/main/java/com/shopify/unity/buy/MockUnityActivity.java
- scripts/test_android.sh
* Fixes up instrumentation tests and removes MockActivity
* Adds connectedDeviceTest to script to test both instrumentation tests and unit tests
* Adds .travis.yml file for device/unit CI on Travis along side iPhone/Unity CI on circle.
> [Android] Fix tests and add Android CI on Travis

- Assets/Editor/BuildPipeline/iOSTestPostProcessor.cs
- Assets/Plugins/iOS/Shopify/BuyTests/ApplePayEventDispatcherTests.swift
- Assets/Plugins/iOS/Shopify/BuyTests/ApplePayFlowTests.swift
- Assets/Plugins/iOS/Shopify/BuyTests/Mocks/MockAuthorizationController.swift
- Assets/Plugins/iOS/Shopify/BuyTests/Mocks/MockPaymentSessionDelegate.swift
- Assets/Plugins/iOS/Shopify/BuyTests/PaymentSessionTests.swift
- circle.yml
- scripts/generator/graphql_generator/csharp/Editor/BuildPipeline/ExtendedPBXProject.cs.erb
- scripts/install_unity.sh
- scripts/test_iOS.sh
- scripts/test_unity.sh
Jeff's work on getting the iOS 11 tests up and running after the Apple Pay migration work.
> [Tests] iOS 11 testing

- scripts/publish.sh
We should be building the Android .AAR plugin library everytime we run publish.
> [Fix] Added android build phase to the publish script

- Assets/Shopify/Examples/Scripts/Panels/CartPanel.cs
- Assets/Shopify/Plugins/Editor/ShopifyDependencies.xml
- android/shopify_buy_plugin/build.gradle
- android/shopify_buy_plugin/src/androidTest/java/com/shopify/unity/buy/androidpay/view/widget/ShippingRatesViewTest.java
- android/shopify_buy_plugin/src/androidTest/java/com/shopify/unity/buy/models/ShippingMethodTest.java
- android/shopify_buy_plugin/src/main/java/com/shopify/unity/buy/androidpay/ConfirmationActivity.java
- android/shopify_buy_plugin/src/main/java/com/shopify/unity/buy/androidpay/UnityAndroidPayFragment.java
- android/shopify_buy_plugin/src/main/java/com/shopify/unity/buy/androidpay/view/viewmodel/ShippingRatesViewModel.java
- android/shopify_buy_plugin/src/main/java/com/shopify/unity/buy/androidpay/view/widget/ShippingMethodSelectDialog.java
- android/shopify_buy_plugin/src/main/java/com/shopify/unity/buy/androidpay/view/widget/ShippingRatesView.java
- android/shopify_buy_plugin/src/main/java/com/shopify/unity/buy/models/AndroidPayEventResponse.java
- android/shopify_buy_plugin/src/main/java/com/shopify/unity/buy/models/PricingLineItems.java
- android/shopify_buy_plugin/src/main/java/com/shopify/unity/buy/models/ShippingMethod.java
- android/shopify_buy_plugin/src/main/java/com/shopify/unity/buy/utils/BigDecimalConverter.java
- android/shopify_buy_plugin/src/main/res/layout/shipping_rate_list.xml
- android/shopify_buy_plugin/src/main/res/layout/shipping_rate_list_item.xml
- android/shopify_buy_plugin/src/main/res/values/colors.xml
- android/shopify_buy_plugin/src/main/res/values/strings.xml
- android/shopify_buy_plugin/src/main/res/values/styles.xml
- android/shopify_buy_plugin/src/test/java/com/shopify/unity/buy/models/AndroidPayEventResponseTest.java
- scripts/generator/graphql_generator/csharp.rb
- scripts/generator/graphql_generator/csharp/Cart.cs.erb
- scripts/generator/graphql_generator/csharp/SDK/Android/AndroidNativeCheckout.AndroidPayEventReceiver.cs.erb
- scripts/generator/graphql_generator/csharp/SDK/Android/AndroidNativeCheckout.cs.erb
- scripts/generator/graphql_generator/csharp/SDK/Android/AndroidPayEventResponse.cs.erb
- scripts/generator/graphql_generator/csharp/SDK/ShippingMethod.cs.erb
This change refers to the task of building the UI to show the list of available shipping methods:
This image is an actual screenshot of the implemented feature. The shipping methods are not being mocked, they are already being provided by Unity.
> Show shipping selector in confirmation screen.

- .gitignore
These files keep being generated by Android Studio.
> Ignore .project files

- android/shopify_buy_plugin/src/androidTest/java/com/shopify/unity/buy/androidpay/AndroidPayCheckoutTest.java
- android/shopify_buy_plugin/src/androidTest/java/com/shopify/unity/buy/androidpay/view/widget/ShippingRatesViewTest.java
- android/shopify_buy_plugin/src/main/java/com/shopify/unity/buy/MessageCenter.java
- android/shopify_buy_plugin/src/main/java/com/shopify/unity/buy/ShopifyUnityPlayerActivity.java
- android/shopify_buy_plugin/src/main/java/com/shopify/unity/buy/androidpay/AndroidPayCheckout.java
- android/shopify_buy_plugin/src/main/java/com/shopify/unity/buy/androidpay/view/viewmodel/ConfirmationViewModel.java
- android/shopify_buy_plugin/src/main/java/com/shopify/unity/buy/androidpay/view/widget/ConfirmationView.java
- android/shopify_buy_plugin/src/main/java/com/shopify/unity/buy/androidpay/view/widget/ShippingMethodSelectDialog.java
- android/shopify_buy_plugin/src/main/java/com/shopify/unity/buy/androidpay/view/widget/ShippingRatesView.java
- android/shopify_buy_plugin/src/main/java/com/shopify/unity/buy/models/CheckoutInfo.java
- android/shopify_buy_plugin/src/main/java/com/shopify/unity/buy/models/ShippingMethod.java
- scripts/generator/graphql_generator/csharp/SDK/Android/AndroidNativeCheckout.AndroidPayEventReceiver.cs.erb
- scripts/generator/graphql_generator/csharp/SDK/Android/AndroidPayEventReceiverBridge.cs.erb
- scripts/generator/graphql_generator/csharp/SDK/ShippingMethod.cs.erb
- scripts/generator/graphql_generator/csharp/SDK/SummaryItem.cs.erb
Whenever the user changes the shipping method, this change is propagated down to Unity to update the cart and then Unity propagates the updated pricing lines back up to refresh the UI.
> Send shipping line to Unity

- .travis.yml
> Update Travis distro

- Assets/Editor/MockLoaderCollections.cs
- Assets/Editor/TestShopify.cs
- scripts/generator/graphql_generator/csharp/SDK/DefaultQueries.cs.erb
- scripts/generator/graphql_generator/csharp/SDK/Delegates.cs.erb
- scripts/generator/graphql_generator/csharp/ShopifyBuy.cs.erb
This PR implements paginated collections in the same way that paginated products work.
> Paginated collections

- Assets/Shopify/UIToolkit/Themes/CollectionTheme.cs
- Assets/Shopify/UIToolkit/Themes/CollectionTheme.cs.meta
A scaffold of methods that should be in the collection theme
> [UI Toolkit] Collection theme scaffolding

- Assets/IntegrationTests/TestGenericQuery.cs
- Assets/IntegrationTests/TestShopifyCollections.cs
- Assets/IntegrationTests/TestShopifyProducts.cs
- Assets/IntegrationTests/TestTimeout.cs
- Assets/IntegrationTests/TestUnityLoader.cs
- Assets/Shopify/UIToolkit/Test/Integration/TestSanity.cs
Fixes compile errors when building project for iOS platform and running test_iOS.sh
> Wrapped integration tests with UNITY_EDITOR check

- .gitignore
- Assets/IntegrationTests/Clients.cs
- Assets/IntegrationTests/Clients.cs.meta
- Assets/IntegrationTests/StoppableWaitForTime.cs
- Assets/IntegrationTests/TestGenericQuery.cs
- Assets/IntegrationTests/TestShopifyCollections.cs
- Assets/IntegrationTests/TestShopifyProducts.cs
- Assets/IntegrationTests/TestUnityLoader.cs
- Assets/IntegrationTests/Utils.cs
- scripts/generator/graphql_generator/csharp/SDK/DefaultQueries.cs.erb
Added some integration tests for pagination. Noticed there was an issue where the same client would be used for two tests which was causing issues where the wrong default client was being used.
> Pagination integration tests

- Assets/Shopify/UIToolkit/Editor.meta
- Assets/Shopify/UIToolkit/Editor/ShopCredentialsVerifier.cs
- Assets/Shopify/UIToolkit/Editor/ShopCredentialsVerifier.cs.meta
- Assets/Shopify/UIToolkit/Interfaces.meta
- Assets/Shopify/UIToolkit/Interfaces/IShopCredentials.cs
- Assets/Shopify/UIToolkit/Interfaces/IShopCredentials.cs.meta
- Assets/Shopify/UIToolkit/ShopCredentialsVerificationState.cs
- Assets/Shopify/UIToolkit/ShopCredentialsVerificationState.cs.meta
- Assets/Shopify/UIToolkit/Test/Unit/Editor/TestShopCredentialsVerifier.cs
- Assets/Shopify/UIToolkit/Test/Unit/Editor/TestShopCredentialsVerifier.cs.meta
This class allows verifying credentials in the editor. It takes a
context object that implement IShopCredentials and is able to make
requests and mutate the verification state on that context object.
It also includes a delegate function for drawing the UI for verifying
credentials, it's designed to be initialized in OnEnable and called out
to in OnInspectorGUI
> [UI Toolkit] Add Class for verifying credentials in the editor

- scripts/generator/graphql_generator/csharp/Editor/ShopifyOnboardingPanel.cs.erb
Fixes #322
Small copy changes to the onboarding panel
> Updates onboarding panel content

- Assets/Shopify/Plugins/Android/libs/buy3-pay-support-1.0.2.aar.meta
- Assets/Shopify/Plugins/Android/libs/shopify_buy_plugin.aar.meta
These files regenerate everytime I open the editor.
> Add some untracked meta files

- Assets/Shopify/UIToolkit/Components/DataCache.cs
- Assets/Shopify/UIToolkit/Components/DataCache.cs.meta
- Assets/Shopify/UIToolkit/Components/HTTPUtils.cs
- Assets/Shopify/UIToolkit/Components/HTTPUtils.cs.meta
- Assets/Shopify/UIToolkit/Components/LRUCache.cs
- Assets/Shopify/UIToolkit/Components/LRUCache.cs.meta
- Assets/Shopify/UIToolkit/Components/RemoteImageLoader.cs
- Assets/Shopify/UIToolkit/Components/WebImageCache.cs
- Assets/Shopify/UIToolkit/Components/WebImageCache.cs.meta
- Assets/Shopify/UIToolkit/Test/Integration/TestRemoteImageLoaderIntegration.cs
- Assets/Shopify/UIToolkit/Test/Integration/TestWebImageCacheIntegration.cs
- Assets/Shopify/UIToolkit/Test/Integration/TestWebImageCacheIntegration.cs.meta
- Assets/Shopify/UIToolkit/Test/Unit/Editor/TestHTTPUtils.cs
- Assets/Shopify/UIToolkit/Test/Unit/Editor/TestHTTPUtils.cs.meta
- Assets/Shopify/UIToolkit/Test/Unit/Editor/TestWebImageCache.cs
- Assets/Shopify/UIToolkit/Test/Unit/Editor/TestWebImageCache.cs.meta
Combination of previously open PRs. Opening this PR to get tests passing before folding into master.
> Web Caching + Smart Image Loading

- Assets/Shopify/UIToolkit/Test/Unit/Editor/TestThemeControllerBase.cs
- Assets/Shopify/UIToolkit/Theme Controllers/SingleProductThemeController.cs
- Assets/Shopify/UIToolkit/Theme Controllers/ThemeControllerBase.cs
- Assets/Shopify/UIToolkit/Themes/Debug/DebugSingleProductTheme.cs
- Assets/Shopify/UIToolkit/Themes/Generic/GenericSingleProductTheme.cs
- Assets/Shopify/UIToolkit/Themes/IShopTheme.cs
- Assets/Shopify/UIToolkit/Themes/IThemeBase.cs
Adds some helper methods for managing the cart with the theme
controller.
> [UI Toolkit] Add cart functionality to base Theme Controller

- Assets/Editor/EditorTimeoutSwitch.cs
- Assets/Editor/TestGraphBuilder.cs
- Assets/Editor/Utils.cs
* Fixes compile errors when running ./scripts/test.sh from command line
* Fixes bug where Apple Pay wasn't appearing on device
> [Fixes] Mono Unit Test compiler issues

- Assets/Shopify/UIToolkit/Editor/ProductPicker.cs
- Assets/Shopify/UIToolkit/Editor/ProductPicker.cs.meta
- Assets/Shopify/UIToolkit/Test/Unit/Editor/TestProductPicker.cs
- Assets/Shopify/UIToolkit/Test/Unit/Editor/TestProductPicker.cs.meta
Implementation of a tool that is to be called within an editor script
that allows the loading and rendering of a product picker within the
editor.
Follows a view/controller pattern that allows us to mock EditorGUI calls
out for tests.
> [UI Toolkit] Editor Utility for showing a product picker in the editor

- README.md
Fixes broken link ‼️ in our readme!
related https://github.com/Shopify/unity-buy-sdk/issues/414
> fix readme broken link

- Assets/Shopify/Unity/Cart.cs
Noticed that Cart's subtotal was not documented.
> Added docs for subtotal

- Assets/IntegrationTests/TestShopifyCollections.cs
- Assets/Shopify/Unity/SDK/Delegates.cs
- Assets/Shopify/Unity/ShopifyBuy.cs
* Adds the ability to pass in a list of collection IDs to query for from the server
> Adds collections by id API to ShopifyBuy.Client

- EXAMPLES.md
Now that ShopifyError is in the top level namespace, we don't need these includes.
> dont need SDK include

- scripts/activate_license.sh
Digging into the license issue, I found out that 1 seat can actually be used on two computers, which is allowed as a redundancy factor (https://answers.unity.com/questions/8063/about-limited-to-running-your-pro-license-on-up-to.html)
At any rate, what I think is happening, having tested this in single, double and multiple CI run scenarios, is that we occasionally hit this limit, and then despite failing this step, we try and run the rest of the build. 
What this PR does it add a delayed retry, which will make 10 progressively longer attempts to get a license, before allowing the scripts to either exit successfully or exit failure.
> [wip] retry license acquisition

- scripts/generator/update_schema
We've been asked to update which endpoint we are using, related Shopify/shopify#129910
related; https://github.com/Shopify/cpp-buy-sdk-next/pull/53
> update storefront api endpoint

- Assets/Shopify/UIToolkit/Test/Unit/Editor/TestShopThemeController.cs
- Assets/Shopify/UIToolkit/Test/Unit/Editor/TestShopThemeController.cs.meta
- Assets/Shopify/UIToolkit/Test/Unit/Editor/TestShopThemeControllerEditor.cs
- Assets/Shopify/UIToolkit/Test/Unit/Editor/TestShopThemeControllerEditor.cs.meta
- Assets/Shopify/UIToolkit/Theme Controllers/Editor/ShopThemeControllerEditor.cs
- Assets/Shopify/UIToolkit/Theme Controllers/Editor/ShopThemeControllerEditor.cs.meta
- Assets/Shopify/UIToolkit/Theme Controllers/ShopThemeController.cs
- Assets/Shopify/UIToolkit/Theme Controllers/ShopThemeController.cs.meta
- Assets/Shopify/UIToolkit/Themes/Generic/Generic Shop Prefab.prefab
- Assets/Shopify/UIToolkit/Themes/Generic/Generic Shop Prefab.prefab.meta
- Assets/Shopify/UIToolkit/Themes/Generic/GenericShopTheme.cs
- Assets/Shopify/UIToolkit/Themes/Generic/GenericShopTheme.cs.meta
Creates a base to work on for the shop theme controller and shop themes.
> [UI Toolkit] Scaffold Shop Theme Files

- Assets/Shopify/UIToolkit/Components/ProductImageHolder.cs
- Assets/Shopify/UIToolkit/Components/ProductImageHolder.cs.meta
- Assets/Shopify/UIToolkit/Components/RemoteImageLoader.cs
- Assets/Shopify/UIToolkit/Themes/Generic/Generic Single Product Theme Landscape.prefab
- Assets/Shopify/UIToolkit/Themes/Generic/GenericSingleProductTheme.cs
- Assets/Shopify/UIToolkit/Themes/Generic/Prefabs/Selected Option.prefab
- Assets/Shopify/UIToolkit/Themes/Generic/Prefabs/Unselected Option.prefab
- Assets/Shopify/Unity/Generated.meta
- Assets/Working.unity
Adds loading of images to the generic single product detail prefab.
> [UI Toolkit] Adds image selection/loading/caching to generic single product detail controller

- Assets/Shopify/UIToolkit/Shops/Generic/Assets/ErrorPopup.meta
- Assets/Shopify/UIToolkit/Shops/Generic/Assets/ErrorPopup/Error Popup Animator Controller.controller
- Assets/Shopify/UIToolkit/Shops/Generic/Assets/ErrorPopup/Error Popup Animator Controller.controller.meta
- Assets/Shopify/UIToolkit/Shops/Generic/Assets/ErrorPopup/Error Popup.prefab
- Assets/Shopify/UIToolkit/Shops/Generic/Assets/ErrorPopup/Error Popup.prefab.meta
- Assets/Shopify/UIToolkit/Shops/Generic/Assets/ErrorPopup/ErrorPopup.cs
- Assets/Shopify/UIToolkit/Shops/Generic/Assets/ErrorPopup/ErrorPopup.cs.meta
- Assets/Shopify/UIToolkit/Shops/Generic/Assets/ErrorPopup/Ready.anim
- Assets/Shopify/UIToolkit/Shops/Generic/Assets/ErrorPopup/Ready.anim.meta
- Assets/Shopify/UIToolkit/Shops/Generic/Assets/ErrorPopup/ShowError.anim
- Assets/Shopify/UIToolkit/Shops/Generic/Assets/ErrorPopup/ShowError.anim.meta
- Assets/Shopify/UIToolkit/Test/Integration/TestErrorPopup.cs
- Assets/Shopify/UIToolkit/Test/Integration/TestErrorPopup.cs.meta
An error message popup component that displayed error messages one by
one. The messages are first checked to see if they are already in the
queue, and if not, they are queued to be displayed.
To tophat it, you can run the integration tests and watch it play in the scene view
> [UI Toolkit] Error Message popup view

- ProjectSettings/ProjectSettings.asset
Commits some ProjectSettings that are changed when you enable playmode
tests in the editor.
> [UIToolkit] Start with playmode test runner enabled

- Assets/Shopify/UIToolkit/Editor/ShopCredentialsVerifier.cs
- Assets/Shopify/UIToolkit/Test/Unit/Editor/TestShopCredentialsVerifier.cs
Changes include a "verifying state", removing the exception that is
thrown when a request is initiated while another is in progress,
Catching all exceptions from the verification process and causing them
to enter a failed state (which stops things like URI parsing errors from
breaking the verifier)
> [UI Toolkit] More robust credentials verification

- Assets/Shopify/UIToolkit/Test/Testing Scene.unity
Adds a simple testing scene with buttons for spawning the single and multi product shop prefabs.
> add ui toolkit testing scene

- Assets/Shopify/UIToolkit/Shops/Generic/Assets/Animation/Generic Shop Animator Controller.controller
- Assets/Shopify/UIToolkit/Shops/Generic/Classes/GenericMultiProductShop.cs
- Assets/Shopify/UIToolkit/Shops/Generic/Classes/GenericSingleProductShop.cs
- Assets/Shopify/UIToolkit/Shops/Generic/Prefabs/Generic Multi Product Shop Landscape.prefab
- Assets/Shopify/UIToolkit/Shops/Generic/Prefabs/Generic Multi Product Shop Landscape.prefab.meta
- Assets/Shopify/UIToolkit/Shops/Generic/Prefabs/Generic Single Product Shop Landscape.prefab
- Assets/Shopify/UIToolkit/Shops/Generic/Prefabs/Generic Single Product Shop Landscape.prefab.meta
- Assets/Shopify/UIToolkit/Test/Testing Scene.unity
Adds and hooks up the show hide functionality for the single product
shop. Also unifies the chrome close buttons and fixes some layout issues
> [UI Toolkit] Unify single product and multi product uis

- Assets/Shopify/Examples/Scripts/LineItems/CartPanelLineItem.cs
- Assets/Shopify/Examples/Scripts/Panels/ProductPanel.cs
- Assets/Shopify/Examples/Scripts/Panels/ProductsPanelCell.cs
- Assets/Shopify/UIToolkit/Shops/Generic/Classes/MultiProductListItem.cs
- Assets/Shopify/UIToolkit/Shops/Generic/Classes/ProductDetailsViewBindings.cs
- Assets/Shopify/Unity/SDK/DefaultCollectionQueries.cs
- Assets/Shopify/Unity/SDK/DefaultProductQueries.cs
- Assets/Shopify/Unity/ShopifyBuy.cs
> update src to transformedSrc

- Assets/Shopify/UIToolkit/Components/ProductCache.cs
- Assets/Shopify/UIToolkit/Test/Unit/Editor/TestProductCache.cs
Adds method to retrieve products by index from cache.
> add Get to ProductCache

- Assets/Shopify/UIToolkit/ShopControllers/BaseShopController.cs
- Assets/Shopify/UIToolkit/ShopControllers/Classes/CartController.cs
- Assets/Shopify/UIToolkit/Shops/Debug/DebugSingleProductShop.cs
- Assets/Shopify/UIToolkit/Shops/Generic/Classes/CartItemView.cs
- Assets/Shopify/UIToolkit/Shops/Generic/Classes/CartView.cs
- Assets/Shopify/UIToolkit/Shops/Generic/Classes/GenericMultiProductShop.cs
- Assets/Shopify/UIToolkit/Shops/Generic/Classes/GenericSingleProductShop.cs
- Assets/Shopify/UIToolkit/Shops/Generic/Views/Cart Panel.prefab
- Assets/Shopify/UIToolkit/Shops/Interfaces/IMultiProductShop.cs
- Assets/Shopify/UIToolkit/Shops/Interfaces/IShop.cs
Connects the increase/decrease quantity buttons from the CartItemViews to the Shop in order to tell the CartController when to change the quantity. When the quantity is changed, the OnCartItemsChanged event is triggers causing the CartView to update.
@JakeCataford I feel like this stuff would fit right into the work your doing in hooking everything up.
> Adds increasing/decreasing of quantities for cart items and a basic empty state

- Assets/Shopify/UIToolkit/Components/RemoteImageLoader.cs
Instead of waiting for 304, we can update the target image right away which, in the common case will result in quicker UI. In the case we need to re-cache, will work same as before.
> fast cache RemoteImageLoader

- Assets/Shopify/UIToolkit/Components/ProductCache.cs.meta
- Assets/Shopify/UIToolkit/ShopControllers/Classes/CartController.cs
- Assets/Shopify/UIToolkit/Shops/Debug/DebugSingleProductShop.cs
- Assets/Shopify/UIToolkit/Shops/Generic/Classes/CartItemView.cs
- Assets/Shopify/UIToolkit/Shops/Generic/Classes/CartView.cs
- Assets/Shopify/UIToolkit/Shops/Generic/Classes/GenericMultiProductShop.cs
- Assets/Shopify/UIToolkit/Shops/Generic/Classes/GenericSingleProductShop.cs
- Assets/Shopify/UIToolkit/Shops/Generic/Classes/ProductDetailsView.cs
- Assets/Shopify/UIToolkit/Shops/Generic/Classes/ProductDetailsViewBindings.cs
- Assets/Shopify/UIToolkit/Shops/Generic/Prefabs/Generic Multi Product Shop Landscape.prefab
- Assets/Shopify/UIToolkit/Shops/Generic/Views/Cart Item Template.prefab
- Assets/Shopify/UIToolkit/Shops/Generic/Views/Cart Item Template.prefab.meta
- Assets/Shopify/UIToolkit/Shops/Generic/Views/Cart Panel.prefab
- Assets/Shopify/UIToolkit/Shops/Generic/Views/Product Details.prefab
- Assets/Shopify/UIToolkit/Shops/Generic/Views/Product List.prefab
- Assets/Shopify/UIToolkit/Shops/Interfaces/IShop.cs
- Assets/Shopify/UIToolkit/Test/Testing Scene.unity
- Assets/Shopify/UIToolkit/Test/Testing Scene.unity.meta
- Assets/Shopify/UIToolkit/Test/Unit/Editor/TestProductCache.cs.meta
- Assets/Shopify/UIToolkit/Test/Unit/Editor/TestShopControllerBase.cs
- Assets/Shopify/UIToolkit/Themes.meta
- Assets/Shopify/UIToolkit/Themes/Generic.meta
- Assets/Shopify/UIToolkit/Themes/Generic/Assets.meta
- ios-build/Unity-iPhone/shoppingdemo.entitlements
This PR fixes a variety of issues with the Cart View:
* CartView now properly animates in and out in the tester scene's multi product shop.
* Fixes background colors for most of the panels including the Cart View
* Fixes bug with toggling of empty state on the Cart
* Fixes Unity crashing issue when trying to make reference to Shop property in CartView
* Small refactor in how we invalidate the Cart View and handle actions for increasing/decreasing
> Multi Shop Product <-> Cart interaction bug fixes

- Assets/Shopify/UIToolkit/Components/ContentRegion.cs
- Assets/Shopify/UIToolkit/Shops/Generic/Classes/GenericMultiProductShop.cs
- Assets/Shopify/UIToolkit/Shops/Generic/Classes/ProductListView.cs
- Assets/Shopify/UIToolkit/Shops/Generic/Views/Product List.prefab
Needs more work refining the UX, but this adds in the infinite pagination!
> add infinite pagination to product list

- Assets/Shopify/UIToolkit/Shops/Generic/Assets/Animation/Badge Animator Controller.controller
- Assets/Shopify/UIToolkit/Shops/Generic/Assets/Animation/Badge Animator Controller.controller.meta
- Assets/Shopify/UIToolkit/Shops/Generic/Assets/Animation/BadgeAdding.anim
- Assets/Shopify/UIToolkit/Shops/Generic/Assets/Animation/BadgeAdding.anim.meta
- Assets/Shopify/UIToolkit/Shops/Generic/Assets/Animation/BadgeHidden.anim
- Assets/Shopify/UIToolkit/Shops/Generic/Assets/Animation/BadgeHidden.anim.meta
- Assets/Shopify/UIToolkit/Shops/Generic/Assets/Animation/BadgeHide.anim
- Assets/Shopify/UIToolkit/Shops/Generic/Assets/Animation/BadgeHide.anim.meta
- Assets/Shopify/UIToolkit/Shops/Generic/Assets/Animation/BadgeShow.anim
- Assets/Shopify/UIToolkit/Shops/Generic/Assets/Animation/BadgeShow.anim.meta
- Assets/Shopify/UIToolkit/Shops/Generic/Assets/Animation/BadgeShown.anim
- Assets/Shopify/UIToolkit/Shops/Generic/Assets/Animation/BadgeShown.anim.meta
- Assets/Shopify/UIToolkit/Shops/Generic/Classes/CartBadgeView.cs
- Assets/Shopify/UIToolkit/Shops/Generic/Classes/GenericMultiProductShop.cs
Add some bobbing animations for the badge on the cart button icon when the user adds/removes items from the cart to give a better sense of feedback.
> Adds bobbing animation to cart icon's badge

- Assets/Shopify/UIToolkit/ShopControllers/Classes/CartController.cs
- Assets/Shopify/UIToolkit/Shops/Generic/Classes/GenericSingleProductShop.cs
- Assets/Shopify/UIToolkit/Shops/Generic/Prefabs/Generic Single Product Shop Landscape.prefab
Small logic bug fix and renames the button on the single product shop page to just 'Buy'
> Fixes bug where checkout wasn't happening on single product shop renamed button to Buy

- Assets/Shopify/UIToolkit/Shops/Generic/Views/Product List.prefab
- Assets/Shopify/UIToolkit/Test/Testing Scene.unity
When I was 🎩 ing master I noticed that the prefab changes that added the scroll rect component back got blown away. This adds it back for scrolling goodness.
> Fixes missing scroll view/script on list view

- Assets/Shopify/UIToolkit/Components/RemoteImageLoader.cs
- Assets/Shopify/UIToolkit/ShopControllers/MultiProductShopController.cs
- Assets/Shopify/UIToolkit/Shops/Generic/Classes/CartView.cs
- Assets/Shopify/UIToolkit/Shops/Generic/Classes/GenericMultiProductShop.cs
- Assets/Shopify/UIToolkit/Shops/Generic/Classes/GenericSingleProductShop.cs
- Assets/Shopify/UIToolkit/Shops/Generic/Classes/MultiProductListItem.cs
- Assets/Shopify/UIToolkit/Shops/Generic/Classes/ProductListView.cs
- Assets/Shopify/UIToolkit/Shops/Generic/Prefabs/Generic Multi Product Shop Landscape.prefab
- Assets/Shopify/UIToolkit/Shops/Generic/Prefabs/Generic Multi Product Shop Landscape.prefab.meta
- Assets/Shopify/UIToolkit/Shops/Generic/Prefabs/Generic Single Product Shop Landscape.prefab
- Assets/Shopify/UIToolkit/Shops/Generic/Prefabs/Generic Single Product Shop Landscape.prefab.meta
- Assets/Shopify/UIToolkit/Shops/Generic/Views/Cart Panel.prefab
- Assets/Shopify/UIToolkit/Shops/Generic/Views/Product Details.prefab
- Assets/Shopify/UIToolkit/Shops/Generic/Views/Product List.prefab
- Assets/Shopify/UIToolkit/Shops/Generic/Views/Product List.prefab.meta
- Assets/Shopify/UIToolkit/Test/Testing Scene.unity
Fixes a bunch of small bugs and tweaks the UI to make everything more shiny. I'll comment inline on what changes were made.
> [UI Toolkit] Big clean up pr

- Assets/Shopify/UIToolkit/Shops/Generic/Classes/ProductDetailsViewBindings.cs
- Assets/Shopify/UIToolkit/Shops/Generic/Views/Cart Panel.prefab
@JakeCataford This should fix up the cart item issue we spoke about this morning as well as another I found when using the variant dropdown selector. Feel free to merge this into your branch before you land yours into master.
> Fixes cart remove/add issue and out of bounds exception in variant dropdown

- Assets/Shopify/Examples/Scenes/Vending Machine Example.unity
Reassigned the AnimationCanvas script to fix some weirdness.
> reassign animation canvas

- EXAMPLES.md
- docs/index.html
> fix getting started link

- Assets/Shopify/Unity/SDK/Editor/UnityEditorLoader.cs
- Assets/Shopify/Unity/SDK/UnityLoader.cs
- scripts/generator/update_schema
> Release package 1.1.0

- Assets/Shopify/Unity/SDK/Editor/UnityEditorLoader.cs
- Assets/Shopify/Unity/SDK/UnityLoader.cs
- scripts/generator/update_schema
**Summary of Changes**
- Point to a newer version of the storefront API graphql endpoint. 
Both unit and integration tests pass locally. 
Tested using sample app locally.
> Update to a newer storefront API version

- scripts/publish.sh
- scripts/test_iOS.sh
- scripts/test_unity.sh
**Errors when running test_iOS.sh and test_unity.sh** 
```
./scripts/publish.sh: line 11: printf: --: invalid option
printf: usage: printf [-v var] format [arguments]
cat: /Users/zuwaomigie/src/github.com/Shopify/unity-buy-sdk/export.log: No such file or directory
```
**Fix**
Add formatter in printf string
> Fix printf error in test_iOS script

- dev.yml
Followed instructions on `dev up` failure.
> Remove openssl from dev.yml

- Assets/Editor/TestShopify.cs
- Assets/IntegrationTests/Clients.cs
- Assets/IntegrationTests/TestUnityLoader.cs
- Assets/Shopify/Examples/Scripts/Helpers/ShopifyHelper.cs
- Assets/Shopify/Examples/Scripts/ShopPopup.cs
- Assets/Shopify/Unity/SDK/BaseLoader.cs
- Assets/Shopify/Unity/SDK/Editor/UnityEditorLoader.cs
- Assets/Shopify/Unity/SDK/UnityLoader.cs
- Assets/Shopify/Unity/ShopifyBuy.cs
- Assets/Shopify/examples.txt.meta
- EXAMPLES.md
- README.md
- scripts/generator/graphql_generator/csharp/type_response.cs.erb
- scripts/generator/update_schema
Point to Storefront API version 2020-01
Tophatted in the Vending Machine scene
> Bump targeted Storefront API version 2020-01
